// Code generated by protoc-gen-go-errcode. DO NOT EDIT.
// versions:
// - protoc-gen-go-errcode v1.0.0
// - protoc             v4.25.2
// source: tests/test.proto

package sms

import "github.com/ml444/gkit/errorx"

var DefaultErrCode = errorx.ErrCodeDetail{
	StatusCode: 200,
	ErrorCode:  12000,
	Message:    "success",
	Polyglot: map[string]string{
		"en": "success",
		"zh": "成功",
	},
}

const (
	ErrInvalidParam       int32 = 12000
	ErrParamRequired      int32 = 12001
	ErrNotFoundSendRecord int32 = 12002
	ErrLimitControl       int32 = 12003
	ErrNotFoundTemplate   int32 = 12004
)

var ErrCodeMap = map[int32]*errorx.ErrCodeDetail{
	ErrInvalidParam: &errorx.ErrCodeDetail{
		StatusCode: 400,
		ErrorCode:  12000,
		Message:    "非法参数",
		Polyglot:   map[string]string{},
	},
	ErrParamRequired: &errorx.ErrCodeDetail{
		StatusCode: 400,
		ErrorCode:  12001,
		Message:    "缺失参数",
		Polyglot:   map[string]string{},
	},
	ErrNotFoundSendRecord: &errorx.ErrCodeDetail{
		StatusCode: 404,
		ErrorCode:  12002,
		Message:    "未找到相关短信记录",
		Polyglot:   map[string]string{},
	},
	ErrLimitControl: &errorx.ErrCodeDetail{
		StatusCode: 403,
		ErrorCode:  12003,
		Message:    "超过了短信发送频率",
		Polyglot:   map[string]string{},
	},
	ErrNotFoundTemplate: &errorx.ErrCodeDetail{
		StatusCode: 404,
		ErrorCode:  12004,
		Message:    "模板不存在",
		Polyglot: map[string]string{
			"en": "not found template",
			"zh": "模板不存在",
		},
	},
}

const (
	ErrWrongVerifyCode      int32 = 12005
	ErrSendDailyLimit       int32 = 12006
	ErrSendInterval         int32 = 12007
	ErrInvalidPhone         int32 = 12008
	ErrSendFailed           int32 = 12009
	ErrInvalidTemplateParam int32 = 12010
)

var ErrCode2Map = map[int32]*errorx.ErrCodeDetail{
	ErrWrongVerifyCode: &errorx.ErrCodeDetail{
		StatusCode: 403,
		ErrorCode:  12005,
		Message:    "验证码错误或已过期",
		Polyglot: map[string]string{
			"en": "the verification code is wrong or expired",
		},
	},
	ErrSendDailyLimit: &errorx.ErrCodeDetail{
		StatusCode: 403,
		ErrorCode:  12006,
		Message:    "验证码发送次数超限",
		Polyglot: map[string]string{
			"en": "The number of times the verification code has been sent exceeds the limit",
		},
	},
	ErrSendInterval: &errorx.ErrCodeDetail{
		StatusCode: 403,
		ErrorCode:  12007,
		Message:    "验证码发送频繁，请稍后再试",
		Polyglot: map[string]string{
			"en": "verification codes are sent frequently, please try again later.",
		},
	},
	ErrInvalidPhone: &errorx.ErrCodeDetail{
		StatusCode: 403,
		ErrorCode:  12008,
		Message:    "非法的手机号码",
		Polyglot: map[string]string{
			"en": "illegal mobile phone number",
		},
	},
	ErrSendFailed: &errorx.ErrCodeDetail{
		StatusCode: 400,
		ErrorCode:  12009,
		Message:    "短信发送失败",
		Polyglot: map[string]string{
			"en": "message failed to send",
		},
	},
	ErrInvalidTemplateParam: &errorx.ErrCodeDetail{
		StatusCode: 400,
		ErrorCode:  12010,
		Message:    "短信模版参数错误",
		Polyglot: map[string]string{
			"en": "sms template parameter error",
		},
	},
}
