// Code generated by protoc-gen-go-errcode. DO NOT EDIT.
// versions:
// - protoc-gen-go-errcode v1.0.0
// - protoc             v3.21.5
// source: tests/test.proto

package sms

const (
	ErrInvalidParam       int32 = 12000
	ErrParamRequired      int32 = 12001
	ErrNotFoundSendRecord int32 = 12002
	ErrLimitControl       int32 = 12003
	ErrNotFoundTemplate   int32 = 12004
)

var ErrCodeMap = map[int32]string{
	ErrInvalidParam:       "非法参数",
	ErrParamRequired:      "缺失参数",
	ErrNotFoundSendRecord: "未找到相关短信记录",
	ErrLimitControl:       "超过了短信发送频率",
	ErrNotFoundTemplate:   "模板不存在",
}

var ErrCodePolyglotMap = map[string]map[string]string{
	"ErrInvalidParam":       {},
	"ErrParamRequired":      {},
	"ErrNotFoundSendRecord": {},
	"ErrLimitControl":       {},
	"ErrNotFoundTemplate": {
		"en": "not found template",
		"zh": "模板不存在",
	},
}

var ErrCode4StatusCodeMap = map[int32]int32{
	ErrInvalidParam:       400,
	ErrParamRequired:      400,
	ErrNotFoundSendRecord: 404,
	ErrLimitControl:       403,
	ErrNotFoundTemplate:   404,
}

const (
	ErrWrongVerifyCode int32 = 12005
)

var ErrMessageMap = map[int32]string{
	ErrWrongVerifyCode: "验证码错误或已过期",
}

var ErrMessagePolyglotMap = map[string]map[string]string{
	"ErrWrongVerifyCode": {},
}

var ErrMessage4StatusCodeMap = map[int32]int32{
	ErrWrongVerifyCode: 403,
}
