// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0--rc2
// source: paginate.proto

package paging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Classic paging mode. Use "Page" and "Size" for paging.
type Paginate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @desc: current page
	Page uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// @desc: page size
	Size uint32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// @desc: total number of data
	Total int64 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	// @desc: When SkipCount is true,
	// even if CurrentPage is equal to 1, don't count the total.
	SkipCount bool `protobuf:"varint,4,opt,name=skip_count,json=skipCount,proto3" json:"skip_count,omitempty"`
}

func (x *Paginate) Reset() {
	*x = Paginate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paginate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Paginate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paginate) ProtoMessage() {}

func (x *Paginate) ProtoReflect() protoreflect.Message {
	mi := &file_paginate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paginate.ProtoReflect.Descriptor instead.
func (*Paginate) Descriptor() ([]byte, []int) {
	return file_paginate_proto_rawDescGZIP(), []int{0}
}

func (x *Paginate) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Paginate) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Paginate) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Paginate) GetSkipCount() bool {
	if x != nil {
		return x.SkipCount
	}
	return false
}

// Scroll: mode. Do not count the total, Use "Size" and "NextToken" for paging.
//
//	through the "NextToken" keep getting the next page until the data is finished.
type Scroll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @desc: page size
	Size uint32 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// @desc: next page token
	NextToken string `protobuf:"bytes,2,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
}

func (x *Scroll) Reset() {
	*x = Scroll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paginate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Scroll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scroll) ProtoMessage() {}

func (x *Scroll) ProtoReflect() protoreflect.Message {
	mi := &file_paginate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scroll.ProtoReflect.Descriptor instead.
func (*Scroll) Descriptor() ([]byte, []int) {
	return file_paginate_proto_rawDescGZIP(), []int{1}
}

func (x *Scroll) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Scroll) GetNextToken() string {
	if x != nil {
		return x.NextToken
	}
	return ""
}

var File_paginate_proto protoreflect.FileDescriptor

var file_paginate_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x22, 0x67, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6b, 0x69, 0x70, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x73, 0x6b, 0x69, 0x70, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x3b, 0x0a, 0x06, 0x53, 0x63, 0x72, 0x6f, 0x6c, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x29,
	0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x6c, 0x34,
	0x34, 0x34, 0x2f, 0x67, 0x6b, 0x69, 0x74, 0x2f, 0x64, 0x62, 0x78, 0x2f, 0x70, 0x61, 0x67, 0x69,
	0x6e, 0x67, 0x3b, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_paginate_proto_rawDescOnce sync.Once
	file_paginate_proto_rawDescData = file_paginate_proto_rawDesc
)

func file_paginate_proto_rawDescGZIP() []byte {
	file_paginate_proto_rawDescOnce.Do(func() {
		file_paginate_proto_rawDescData = protoimpl.X.CompressGZIP(file_paginate_proto_rawDescData)
	})
	return file_paginate_proto_rawDescData
}

var file_paginate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_paginate_proto_goTypes = []interface{}{
	(*Paginate)(nil), // 0: paging.Paginate
	(*Scroll)(nil),   // 1: paging.Scroll
}
var file_paginate_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_paginate_proto_init() }
func file_paginate_proto_init() {
	if File_paginate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_paginate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Paginate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paginate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Scroll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_paginate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_paginate_proto_goTypes,
		DependencyIndexes: file_paginate_proto_depIdxs,
		MessageInfos:      file_paginate_proto_msgTypes,
	}.Build()
	File_paginate_proto = out.File
	file_paginate_proto_rawDesc = nil
	file_paginate_proto_goTypes = nil
	file_paginate_proto_depIdxs = nil
}
