package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"strings"
	"text/template"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"

	"github.com/ml444/gkit/cmd/protoc-gen-go-errcode/err"
)

const release = "v1.0.0"
const deprecationComment = "// Deprecated: Do not use."

//go:embed errcode.tmpl
var errcodeTemplate string

func protocVersion(gen *protogen.Plugin) string {
	v := gen.Request.GetCompilerVersion()
	if v == nil {
		return "(unknown)"
	}
	var suffix string
	if s := v.GetSuffix(); s != "" {
		suffix = "-" + s
	}
	return fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix)
}

func genFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	if len(file.Enums) == 0 {
		return nil
	}
	filename := file.GeneratedFilenamePrefix + "_errcode.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-errcode. DO NOT EDIT.")
	g.P("// versions:")
	g.P(fmt.Sprintf("// - protoc-gen-go-errcode %s", release))
	g.P("// - protoc             ", protocVersion(gen))
	if file.Proto.GetOptions().GetDeprecated() {
		g.P("// ", file.Desc.Path(), " is a deprecated file.")
	} else {
		g.P("// source: ", file.Desc.Path())
	}
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P(`import "github.com/ml444/gkit/errorx"`)
	genContent(file, g)
	return g
}

func genContent(file *protogen.File, g *protogen.GeneratedFile) {
	tmpl, e := template.New("errcode").Parse(strings.TrimSpace(errcodeTemplate))
	if e != nil {
		panic(e.Error())
	}
	for _, enum := range file.Enums {
		genErrcode(tmpl, g, enum)
	}
}

type ErrDesc struct {
	EnumName string
	Fields   []ErrField
	Options  *Opts
}
type ErrField struct {
	Name     string
	ErrCode  int32
	Status   int32
	Message  string
	Polyglot map[string]string
}
type Opts struct {
	ErrcodeBegin int32
	ErrCodeEnd   int32
}

func genErrcode(tmpl *template.Template, g *protogen.GeneratedFile, enum *protogen.Enum) {
	if enum.Desc.Options().(*descriptorpb.EnumOptions).GetDeprecated() {
		g.P("//")
		g.P(deprecationComment)
	}
	ed := &ErrDesc{
		EnumName: enum.GoIdent.GoName,
		Fields:   make([]ErrField, 0),
	}
	opts := Opts{
		ErrcodeBegin: 1,
		ErrCodeEnd:   1<<31 - 1,
	}
	if errcodeBegin, ok := proto.GetExtension(enum.Desc.Options(), err.E_LowerBound).(int32); ok && errcodeBegin != 0 {
		opts.ErrcodeBegin = errcodeBegin
	}
	if errcodeEnd, ok := proto.GetExtension(enum.Desc.Options(), err.E_UpperBound).(int32); ok && errcodeEnd != 0 {
		opts.ErrCodeEnd = errcodeEnd
	}
	ed.Options = &opts

	for i, enumValue := range enum.Values {
		vInt32 := int32(enumValue.Desc.Number())
		if vInt32 == 0 {
			if i == 0 {
				continue
			} else {
				println(enumValue.GoIdent.GoName, " errcode must not be 0")
			}
		}
		if vInt32 < opts.ErrcodeBegin || vInt32 > opts.ErrCodeEnd {
			println(fmt.Sprintf("errcode [%d] out of range", vInt32))
		}

		errDetail, ok := proto.GetExtension(enumValue.Desc.Options(), err.E_Detail).(*err.ErrDetail)
		if ok && errDetail != nil {
			fieldName := enumValue.GoIdent.GoName
			fieldName = strings.TrimPrefix(fieldName, enum.GoIdent.GoName+"_")
			m := make(map[string]string)
			for _, polyglot := range errDetail.Polyglot {
				kv := strings.SplitN(polyglot, "=", 2)
				if len(kv) == 2 {
					m[kv[0]] = kv[1]
				}
			}
			ed.Fields = append(ed.Fields, ErrField{
				Name:     fieldName,
				ErrCode:  int32(enumValue.Desc.Number()),
				Status:   statusValue(errDetail.Status),
				Message:  messageValue(errDetail.Message, fieldName),
				Polyglot: m,
			})
		}
	}
	if len(ed.Fields) != 0 {
		buf := new(bytes.Buffer)
		e := tmpl.Execute(buf, ed)
		if e != nil {
			panic(e.Error())
		}
		_, e = g.Write(buf.Bytes())
		if e != nil {
			panic(e.Error())
		}
	}
}

func statusValue(statusCode *int32) int32 {
	if statusCode == nil {
		return 400
	}
	return *statusCode
}
func messageValue(message *string, defaultValue string) string {
	if message == nil {
		return defaultValue
	}
	return *message
}
