package funcs

var FuncMap = map[string]interface{}{
	//"disabled": Disabled,
	//"ignored":  Ignored,
	"required":  RequiredOneOf,
	"has":       Has,
	"needs":     Needs,
	"fileneeds": FileNeeds,
	"isEnum":    isEnum,
	"enumList":  enumList,
	"enumVal":   enumVal,

	"accessor":      accessor,
	"byteStr":       byteStr,
	"cmt":           C80,
	"durGt":         durGt,
	"durLit":        durLit,
	"durStr":        durStr,
	"err":           err,
	"errCause":      errCause,
	"errIdx":        errIdx,
	"inKey":         inKey,
	"inType":        inType,
	"isBytes":       isBytes,
	"lit":           lit,
	"lookup":        lookup,
	"oneOfType":     oneOfTypeName,
	"ruleType":      MapTypeName,
	"tsGt":          tsGt,
	"tsLit":         tsLit,
	"tsStr":         tsStr,
	"externalEnums": externalEnums,
	"enumName":      enumName,
	"enumPackages":  enumPackages,

	"GetImports":  GetImports,
	"OnType":      OnType,
	"GetElemRule": GetElemRule,
	"inKind":      inKind,
	"SetAccessor": SetAccessor,
}
