package funcs

var FuncMap = map[string]interface{}{
	//"disabled": Disabled,
	//"ignored":  Ignored,
	"required":  RequiredOneOf,
	"has":       Has,
	"isEnum":    isEnum,
	"enumList":  enumList,
	"enumVal":   enumVal,

	"byteStr":       byteStr,
	"cmt":           C80,
	"durGt":         durGt,
	"durLit":        durLit,
	"durStr":        durStr,
	"inKey":         inKey,
	"inType":        inType,
	"isBytes":       isBytes,
	"lit":           lit,
	"lookup":        lookup,
	"oneOfType":     oneOfTypeName,
	"tsGt":          tsGt,
	"tsLit":         tsLit,
	"tsStr":         tsStr,
	"enumName": EnumName,
	"inKind":   inKind,
	"JoinString":   JoinString,
	"GetAliasName":       GetAliasName,
	"fail":               Fail,
	"hasWellKnownRegex":  HasWellKnownRegex,
	"wellKnownRegexLit":  WellKnownRegexLit,
	"wellKnownRegexErrMsg": WellKnownRegexErrMsg,
}
