package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"sort"
	"strings"
	"unicode"

	"github.com/ml444/gkit/cmd/protoc-gen-go-errcode/err"

	"google.golang.org/protobuf/reflect/protoreflect"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"

	"github.com/ml444/gkit/cmd/protoc-gen-go-validate/ctx"
	"github.com/ml444/gkit/cmd/protoc-gen-go-validate/funcs"
	"github.com/ml444/gkit/cmd/protoc-gen-go-validate/v"
)

//go:embed validate.tmpl
var validateTemplate string

const Version = "1.0.0"

func generateFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	if len(file.Messages) == 0 {
		return nil
	}
	filename := file.GeneratedFilenamePrefix + "_validate.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-validate. DO NOT EDIT.")
	g.P(fmt.Sprintf("// - protoc-gen-go-validate %s", Version))
	g.P("// - protoc             ", protocVersion(gen))
	if file.Proto.GetOptions().GetDeprecated() {
		g.P("// ", file.Desc.Path(), " is a deprecated file.")
	} else {
		g.P("// source: ", file.Desc.Path())
	}
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	dirs := strings.Split(file.GeneratedFilenamePrefix, "/")
	fileName := dirs[len(dirs)-1]
	funcs.ResetFileState(fileName, string(file.GoPackageName))

	if err := generateFileContent(gen, file, g, fileName); err != nil {
		gen.Error(err)
		return nil
	}
	return g
}

func generateFileContent(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile, fileName string) error {
	if len(file.Messages) == 0 {
		return nil
	}

	validateCtx := &ctx.ValidateCtx{
		FileAliasName: fileName,
		PackageName:   string(file.GoPackageName),
	}
	validateCtx.ErrCodeBegin = getErrCodeBegin(file)

	needWKn := &ctx.NeedWellKnown{}
	importMap := make(map[string]string)
	for _, message := range file.Messages {
		need, msgCtx, imports := genMessage(file, message, needWKn)
		if !need {
			continue
		}
		validateCtx.Messages = append(validateCtx.Messages, msgCtx)
		for _, imp := range imports {
			importMap[imp.Path] = imp.Alias
		}
	}
	validateCtx.Messages = flattenMessages(validateCtx.Messages)
	trackStdImports(validateCtx, needWKn)

	paths := make([]string, 0, len(importMap))
	for path := range importMap {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, path := range paths {
		validateCtx.Imports = append(validateCtx.Imports, &ctx.ImportCtx{Alias: importMap[path], Path: path})
	}
	validateCtx.Imports = append(validateCtx.Imports, &ctx.ImportCtx{Alias: "", Path: "github.com/ml444/gkit/errorx"})
	validateCtx.NeedWellKnow = needWKn

	tmpl, err := getFileTemplate()
	if err != nil {
		return fmt.Errorf("parse validate template: %w", err)
	}
	buf := new(bytes.Buffer)
	if err := tmpl.Lookup("validate").Execute(buf, validateCtx); err != nil {
		return fmt.Errorf("execute validate template for %s: %w", file.Desc.Path(), err)
	}
	if _, err := g.Write(buf.Bytes()); err != nil {
		return fmt.Errorf("write validate output for %s: %w", file.Desc.Path(), err)
	}
	return nil
}

func flattenMessages(msgs []*ctx.MessageCtx) []*ctx.MessageCtx {
	var out []*ctx.MessageCtx
	for _, m := range msgs {
		out = append(out, m)
		if len(m.SubMessageCtxs) > 0 {
			out = append(out, flattenMessages(m.SubMessageCtxs)...)
		}
	}
	return out
}

func trackStdImports(vctx *ctx.ValidateCtx, wk *ctx.NeedWellKnown) {
	needs := &ctx.NeedStdImports{
		Errors:  len(vctx.Messages) > 0,
		Fmt:     len(vctx.Messages) > 0,
		Strings: len(vctx.Messages) > 0,
	}
	if wk.Email || wk.Hostname {
		needs.Errors = true
		needs.Strings = true
		needs.Fmt = true
	}
	if wk.Email {
		needs.Mail = true
	}
	if wk.Hostname || wk.UUID {
		needs.Regexp = true
	}
	if wk.UUID {
		needs.Regexp = true
		needs.Strings = true
	}
	for _, msg := range vctx.Messages {
		for _, f := range msg.Fields {
			trackFieldStdImports(needs, f)
		}
	}
	vctx.NeedStdImports = needs
}

func trackFieldStdImports(needs *ctx.NeedStdImports, f *ctx.FieldCtx) {
	switch f.TmplName {
	case "string":
		needs.Utf8 = true
		needs.Strings = true
		needs.Regexp = true
		needs.Net = true
		needs.Url = true
	case "bytes":
		needs.Bytes = true
	case "map", "repeated":
		needs.Sort = true
	case "duration", "timestamp":
		needs.Time = true
	}
	if f.Rules != nil {
		if hasRuleField(f.Rules, "Pattern") || hasRuleField(f.Rules, "In") || hasRuleField(f.Rules, "NotIn") {
			needs.Regexp = true
		}
		if sr, ok := f.Rules.(*v.StringRules); ok && sr.GetWellKnownRegex() != v.KnownRegex_UNKNOWN {
			needs.Regexp = true
		}
	}
}

func hasRuleField(msg proto.Message, name string) bool {
	if msg == nil {
		return false
	}
	return funcs.Has(msg, name)
}

func getErrCodeBegin(file *protogen.File) int32 {
	for _, enum := range file.Enums {
		if errcode, ok := proto.GetExtension(enum.Desc.Options(), err.E_LowerBound).(int32); ok {
			if errcode != 0 {
				return errcode
			}
		}
	}
	return 0
}

func genMessage(file *protogen.File, message *protogen.Message, needWKn *ctx.NeedWellKnown) (bool, *ctx.MessageCtx, []*ctx.ImportCtx) {
	var imports []*ctx.ImportCtx
	msgCtx := &ctx.MessageCtx{
		Desc:           message.Desc,
		TypeName:       message.GoIdent.GoName,
		NonOneOfFields: []*ctx.FieldCtx{},
		RealOneOfs:     map[string]*ctx.OneOfField{},
		OptionalFields: []*ctx.FieldCtx{},
	}
	disabled, ok := proto.GetExtension(message.Desc.Options(), v.E_Disabled).(bool)
	if ok {
		msgCtx.Disabled = disabled
	}
	ignored, ok := proto.GetExtension(message.Desc.Options(), v.E_Ignored).(bool)
	if ok {
		msgCtx.Ignored = ignored
	}
	var needGen bool
	for _, field := range message.Fields {
		rule, ok := proto.GetExtension(field.Desc.Options(), v.E_Rules).(*v.FieldRules)
		if ok && rule != nil {
			needWellKnown(field.Desc, rule, needWKn)
			needGen = true
			ruleType, ruleIns, messageRule, wrapped := ctx.ResolveRules(field.Desc, rule)
			fieldCtx := ctx.FieldCtx{
				Desc:     field.Desc,
				Field:    field,
				Rules:    ruleIns,
				Name:     field.GoName,
				Type:     field.Desc.Kind().String(),
				TmplName: ruleType,
				Err:      nil,
			}
			importCtx := fieldCtx.ImpCtx()
			if importCtx != nil {
				imports = append(imports, importCtx)
			}
			if imp := importCtxForEnum(field.Enum, file); imp != nil {
				imports = append(imports, imp)
				funcs.ExtraPkg[string(field.Enum.Desc.ParentFile().FullName())] = imp.Alias
				funcs.ExtraPkgPath[imp.Alias] = imp.Path
			}
			if field.Message != nil {
				if imp := importCtxForMessage(field.Message, file); imp != nil {
					imports = append(imports, imp)
					funcs.ExtraPkg[string(field.Message.Desc.ParentFile().FullName())] = imp.Alias
					funcs.ExtraPkgPath[imp.Alias] = imp.Path
				}
			}
			if rule.Errcode != nil {
				fieldCtx.ErrCode = *rule.Errcode
			}
			if wrapped {
				fieldCtx.Wrap = ruleType
				fieldCtx.TmplName = "wrapper"
			}
			if field.Enum != nil {
				fieldCtx.Type = field.Enum.GoIdent.GoName
			} else if field.Message != nil {
				fieldCtx.Type = field.Message.GoIdent.GoName
			}

			if messageRule != nil {
				if messageRule.Required != nil {
					fieldCtx.Required = *messageRule.Required
				}
				if messageRule.Skip != nil {
					fieldCtx.Skip = *messageRule.Skip
				}
			}
			msgCtx.Fields = append(msgCtx.Fields, &fieldCtx)
			if field.Oneof != nil {
				if isOptional(field) {
					msgCtx.OptionalFields = append(msgCtx.OptionalFields, &fieldCtx)
				} else {
					handleOneOfs(field, &fieldCtx, msgCtx)
				}
			} else {
				msgCtx.NonOneOfFields = append(msgCtx.NonOneOfFields, &fieldCtx)
			}
		} else {
			if field.Oneof != nil {
				if isOptional(field) {
					continue
				}
				fieldCtx := ctx.FieldCtx{
					Desc:     field.Desc,
					Field:    field,
					Rules:    nil,
					Name:     field.GoName,
					Type:     field.Desc.Kind().String(),
					TmplName: "none",
					Err:      nil,
				}
				handleOneOfs(field, &fieldCtx, msgCtx)
			}
		}
	}

	for _, msg := range message.Messages {
		need, subMsgCtx, subImports := genMessage(file, msg, needWKn)
		if !need {
			continue
		}
		msgCtx.SubMessageCtxs = append(msgCtx.SubMessageCtxs, subMsgCtx)
		imports = append(imports, subImports...)
		// Retain this (possibly rule-less) parent so nested messages that DO
		// have rules are not dropped together with it. The parent gets a
		// no-op Validate(), and the nested validators are emitted.
		needGen = true
	}
	return needGen, msgCtx, imports
}

func isOptional(field *protogen.Field) bool {
	if field.Desc.Cardinality() != protoreflect.Optional {
		return false
	}
	if fieldName := field.Desc.JSONName(); unicode.IsUpper(rune(fieldName[0])) {
		if strings.HasPrefix(string(field.Oneof.Desc.Name()), "X_") {
			return true
		}
	} else if strings.HasPrefix(string(field.Oneof.Desc.Name()), "_") {
		return true
	}
	return false
}

func needWellKnown(f protoreflect.FieldDescriptor, rules *v.FieldRules, wk *ctx.NeedWellKnown) {
	strRules := collectStringRules(f, rules)
	if strRules != nil {
		if strRules.GetEmail() {
			wk.Email = true
		}
		if strRules.GetHostname() || strRules.GetAddress() {
			wk.Hostname = true
		}
		if strRules.GetUuid() {
			wk.UUID = true
		}
	}
}

func collectStringRules(f protoreflect.FieldDescriptor, rules *v.FieldRules) *v.StringRules {
	if rules == nil {
		return nil
	}
	switch {
	case f.IsList() && f.Kind() == protoreflect.StringKind:
		if r := rules.GetRepeated(); r != nil && r.GetItems() != nil {
			return r.GetItems().GetString_()
		}
	case f.IsMap():
		if r := rules.GetMap(); r != nil {
			if f.MapKey().Kind() == protoreflect.StringKind && r.GetKeys() != nil {
				return r.GetKeys().GetString_()
			}
			if f.MapValue().Kind() == protoreflect.StringKind && r.GetValues() != nil {
				return r.GetValues().GetString_()
			}
		}
	case f.Kind() == protoreflect.StringKind:
		return rules.GetString_()
	default:
		return rules.GetString_()
	}
	return nil
}

func handleOneOfs(field *protogen.Field, fieldCtx *ctx.FieldCtx, msgData *ctx.MessageCtx) {
	oneOf, ok := msgData.RealOneOfs[field.Oneof.GoName]
	if !ok {
		oneOf = &ctx.OneOfField{
			Fields: nil,
			Field:  field,
			Name:   field.Oneof.GoName,
			Type:   string(field.Oneof.Desc.Name()),
		}
	}
	required, ok := proto.GetExtension(field.Oneof.Desc.Options(), v.E_Required).(bool)
	if ok {
		oneOf.Required = required
	}
	oneOf.Fields = append(oneOf.Fields, fieldCtx)
	msgData.RealOneOfs[oneOf.Name] = oneOf
}

func importCtxForEnum(enum *protogen.Enum, current *protogen.File) *ctx.ImportCtx {
	if enum == nil {
		return nil
	}
	impPath := enum.GoIdent.GoImportPath
	if impPath == "" || impPath == current.GoImportPath {
		return nil
	}
	alias := funcs.AllocPkgAlias(goPackageAlias(enum.Desc.ParentFile()))
	return &ctx.ImportCtx{
		Alias: alias,
		Path:  string(impPath),
	}
}

func importCtxForMessage(msg *protogen.Message, current *protogen.File) *ctx.ImportCtx {
	if msg == nil {
		return nil
	}
	impPath := msg.GoIdent.GoImportPath
	if impPath == "" || impPath == current.GoImportPath {
		return nil
	}
	alias := funcs.AllocPkgAlias(goPackageAlias(msg.Desc.ParentFile()))
	return &ctx.ImportCtx{
		Alias: alias,
		Path:  string(impPath),
	}
}

func goPackageAlias(fileDesc protoreflect.FileDescriptor) string {
	opts, ok := fileDesc.Options().(*descriptorpb.FileOptions)
	if !ok || opts.GoPackage == nil {
		return string(fileDesc.Package())
	}
	parts := strings.SplitN(*opts.GoPackage, ";", 2)
	if len(parts) == 2 && parts[1] != "" {
		return parts[1]
	}
	base := parts[0]
	if i := strings.LastIndex(base, "/"); i >= 0 {
		return base[i+1:]
	}
	return base
}

func protocVersion(gen *protogen.Plugin) string {
	ver := gen.Request.GetCompilerVersion()
	if ver == nil {
		return "(unknown)"
	}
	var suffix string
	if s := ver.GetSuffix(); s != "" {
		suffix = "-" + s
	}
	return fmt.Sprintf("v%d.%d.%d%s", ver.GetMajor(), ver.GetMinor(), ver.GetPatch(), suffix)
}
