// Code generated by protoc-gen-go-validate. DO NOT EDIT.
// - protoc-gen-go-validate 1.0.0
// - protoc             v6.30.2
// source: cases/bool.proto

package cases

import (
	"errors"
	"fmt"
	"strings"

	"github.com/ml444/gkit/errorx"
)

// ensure the imports are used
var (
	_ = errors.New("")
	_ = fmt.Print
	_ = (*strings.Reader)(nil)
)

func boolValidationError(errCode int32, msg string, cause error) error {
	err := errorx.CreateError(400, errCode, msg)
	if cause != nil {
		err = err.WithCause(cause)
	}
	return err
}

// boolMultiError is an error wrapping multiple validation errors
// returned by .ValidateAll() if the designated constraints aren't met.
type boolMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m boolMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m boolMultiError) AllErrors() []error { return m }

func (m *BoolConstTrue) Validate() error {
	return m.validate(false)
}

func (m *BoolConstTrue) ValidateAll() error {
	return m.validate(true)
}

func (m *BoolConstTrue) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	if m.GetVal() != true {
		err := boolValidationError(
			0,
			fmt.Sprintf("[Val] value must equal %s", true),
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return boolMultiError(errors)
	}
	return nil
}

func (m *BoolConstFalse) Validate() error {
	return m.validate(false)
}

func (m *BoolConstFalse) ValidateAll() error {
	return m.validate(true)
}

func (m *BoolConstFalse) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	if m.GetVal() != false {
		err := boolValidationError(
			0,
			fmt.Sprintf("[Val] value must equal %s", false),
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return boolMultiError(errors)
	}
	return nil
}
