// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: cases/bool.proto

package cases

import (
	reflect "reflect"
	sync "sync"

	_ "github.com/ml444/gkit/cmd/protoc-gen-go-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BoolNone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val bool `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *BoolNone) Reset() {
	*x = BoolNone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cases_bool_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoolNone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolNone) ProtoMessage() {}

func (x *BoolNone) ProtoReflect() protoreflect.Message {
	mi := &file_cases_bool_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolNone.ProtoReflect.Descriptor instead.
func (*BoolNone) Descriptor() ([]byte, []int) {
	return file_cases_bool_proto_rawDescGZIP(), []int{0}
}

func (x *BoolNone) GetVal() bool {
	if x != nil {
		return x.Val
	}
	return false
}

type BoolConstTrue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val bool `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *BoolConstTrue) Reset() {
	*x = BoolConstTrue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cases_bool_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoolConstTrue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolConstTrue) ProtoMessage() {}

func (x *BoolConstTrue) ProtoReflect() protoreflect.Message {
	mi := &file_cases_bool_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolConstTrue.ProtoReflect.Descriptor instead.
func (*BoolConstTrue) Descriptor() ([]byte, []int) {
	return file_cases_bool_proto_rawDescGZIP(), []int{1}
}

func (x *BoolConstTrue) GetVal() bool {
	if x != nil {
		return x.Val
	}
	return false
}

type BoolConstFalse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val bool `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *BoolConstFalse) Reset() {
	*x = BoolConstFalse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cases_bool_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoolConstFalse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolConstFalse) ProtoMessage() {}

func (x *BoolConstFalse) ProtoReflect() protoreflect.Message {
	mi := &file_cases_bool_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolConstFalse.ProtoReflect.Descriptor instead.
func (*BoolConstFalse) Descriptor() ([]byte, []int) {
	return file_cases_bool_proto_rawDescGZIP(), []int{2}
}

func (x *BoolConstFalse) GetVal() bool {
	if x != nil {
		return x.Val
	}
	return false
}

var File_cases_bool_proto protoreflect.FileDescriptor

var file_cases_bool_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x61, 0x73, 0x65, 0x73, 0x2f, 0x62, 0x6f, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0b, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x63, 0x61, 0x73, 0x65, 0x73, 0x1a,
	0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1c, 0x0a, 0x08, 0x42, 0x6f, 0x6f, 0x6c,
	0x4e, 0x6f, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x2a, 0x0a, 0x0d, 0x42, 0x6f, 0x6f, 0x6c, 0x43, 0x6f,
	0x6e, 0x73, 0x74, 0x54, 0x72, 0x75, 0x65, 0x12, 0x19, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x6a, 0x02, 0x08, 0x01, 0x52, 0x03, 0x76,
	0x61, 0x6c, 0x22, 0x2b, 0x0a, 0x0e, 0x42, 0x6f, 0x6f, 0x6c, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x46,
	0x61, 0x6c, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x6a, 0x02, 0x08, 0x00, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x42,
	0x47, 0x5a, 0x45, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x6c,
	0x34, 0x34, 0x34, 0x2f, 0x67, 0x6b, 0x69, 0x74, 0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x2d, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x63, 0x61, 0x73, 0x65, 0x73, 0x2f,
	0x67, 0x6f, 0x3b, 0x63, 0x61, 0x73, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cases_bool_proto_rawDescOnce sync.Once
	file_cases_bool_proto_rawDescData = file_cases_bool_proto_rawDesc
)

func file_cases_bool_proto_rawDescGZIP() []byte {
	file_cases_bool_proto_rawDescOnce.Do(func() {
		file_cases_bool_proto_rawDescData = protoimpl.X.CompressGZIP(file_cases_bool_proto_rawDescData)
	})
	return file_cases_bool_proto_rawDescData
}

var file_cases_bool_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cases_bool_proto_goTypes = []interface{}{
	(*BoolNone)(nil),       // 0: tests.cases.BoolNone
	(*BoolConstTrue)(nil),  // 1: tests.cases.BoolConstTrue
	(*BoolConstFalse)(nil), // 2: tests.cases.BoolConstFalse
}
var file_cases_bool_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cases_bool_proto_init() }
func file_cases_bool_proto_init() {
	if File_cases_bool_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cases_bool_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoolNone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cases_bool_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoolConstTrue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cases_bool_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoolConstFalse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cases_bool_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cases_bool_proto_goTypes,
		DependencyIndexes: file_cases_bool_proto_depIdxs,
		MessageInfos:      file_cases_bool_proto_msgTypes,
	}.Build()
	File_cases_bool_proto = out.File
	file_cases_bool_proto_rawDesc = nil
	file_cases_bool_proto_goTypes = nil
	file_cases_bool_proto_depIdxs = nil
}
