// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: cases/enums.proto

package cases

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	other_package "github.com/ml444/gkit/cmd/protoc-gen-go-validate/tests/cases/other_package"
	sort "github.com/ml444/gkit/cmd/protoc-gen-go-validate/tests/cases/sort"
	yet_another_package "github.com/ml444/gkit/cmd/protoc-gen-go-validate/tests/cases/yet_another_package"
	_ "github.com/ml444/gkit/cmd/protoc-gen-go-validate/v"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestEnum int32

const (
	TestEnum_ZERO TestEnum = 0
	TestEnum_ONE  TestEnum = 1
	TestEnum_TWO  TestEnum = 2
)

// Enum value maps for TestEnum.
var (
	TestEnum_name = map[int32]string{
		0: "ZERO",
		1: "ONE",
		2: "TWO",
	}
	TestEnum_value = map[string]int32{
		"ZERO": 0,
		"ONE":  1,
		"TWO":  2,
	}
)

func (x TestEnum) Enum() *TestEnum {
	p := new(TestEnum)
	*p = x
	return p
}

func (x TestEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_cases_enums_proto_enumTypes[0].Descriptor()
}

func (TestEnum) Type() protoreflect.EnumType {
	return &file_cases_enums_proto_enumTypes[0]
}

func (x TestEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestEnum.Descriptor instead.
func (TestEnum) EnumDescriptor() ([]byte, []int) {
	return file_cases_enums_proto_rawDescGZIP(), []int{0}
}

type TestEnumAlias int32

const (
	TestEnumAlias_A     TestEnumAlias = 0
	TestEnumAlias_B     TestEnumAlias = 1
	TestEnumAlias_C     TestEnumAlias = 2
	TestEnumAlias_ALPHA TestEnumAlias = 0
	TestEnumAlias_BETA  TestEnumAlias = 1
	TestEnumAlias_GAMMA TestEnumAlias = 2
)

// Enum value maps for TestEnumAlias.
var (
	TestEnumAlias_name = map[int32]string{
		0: "A",
		1: "B",
		2: "C",
		// Duplicate value: 0: "ALPHA",
		// Duplicate value: 1: "BETA",
		// Duplicate value: 2: "GAMMA",
	}
	TestEnumAlias_value = map[string]int32{
		"A":     0,
		"B":     1,
		"C":     2,
		"ALPHA": 0,
		"BETA":  1,
		"GAMMA": 2,
	}
)

func (x TestEnumAlias) Enum() *TestEnumAlias {
	p := new(TestEnumAlias)
	*p = x
	return p
}

func (x TestEnumAlias) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestEnumAlias) Descriptor() protoreflect.EnumDescriptor {
	return file_cases_enums_proto_enumTypes[1].Descriptor()
}

func (TestEnumAlias) Type() protoreflect.EnumType {
	return &file_cases_enums_proto_enumTypes[1]
}

func (x TestEnumAlias) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestEnumAlias.Descriptor instead.
func (TestEnumAlias) EnumDescriptor() ([]byte, []int) {
	return file_cases_enums_proto_rawDescGZIP(), []int{1}
}

type EnumNone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           TestEnum               `protobuf:"varint,1,opt,name=val,proto3,enum=tests.cases.TestEnum" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumNone) Reset() {
	*x = EnumNone{}
	mi := &file_cases_enums_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumNone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumNone) ProtoMessage() {}

func (x *EnumNone) ProtoReflect() protoreflect.Message {
	mi := &file_cases_enums_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumNone.ProtoReflect.Descriptor instead.
func (*EnumNone) Descriptor() ([]byte, []int) {
	return file_cases_enums_proto_rawDescGZIP(), []int{0}
}

func (x *EnumNone) GetVal() TestEnum {
	if x != nil {
		return x.Val
	}
	return TestEnum_ZERO
}

type EnumConst struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           TestEnum               `protobuf:"varint,1,opt,name=val,proto3,enum=tests.cases.TestEnum" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumConst) Reset() {
	*x = EnumConst{}
	mi := &file_cases_enums_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumConst) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumConst) ProtoMessage() {}

func (x *EnumConst) ProtoReflect() protoreflect.Message {
	mi := &file_cases_enums_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumConst.ProtoReflect.Descriptor instead.
func (*EnumConst) Descriptor() ([]byte, []int) {
	return file_cases_enums_proto_rawDescGZIP(), []int{1}
}

func (x *EnumConst) GetVal() TestEnum {
	if x != nil {
		return x.Val
	}
	return TestEnum_ZERO
}

type EnumAliasConst struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           TestEnumAlias          `protobuf:"varint,1,opt,name=val,proto3,enum=tests.cases.TestEnumAlias" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumAliasConst) Reset() {
	*x = EnumAliasConst{}
	mi := &file_cases_enums_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumAliasConst) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumAliasConst) ProtoMessage() {}

func (x *EnumAliasConst) ProtoReflect() protoreflect.Message {
	mi := &file_cases_enums_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumAliasConst.ProtoReflect.Descriptor instead.
func (*EnumAliasConst) Descriptor() ([]byte, []int) {
	return file_cases_enums_proto_rawDescGZIP(), []int{2}
}

func (x *EnumAliasConst) GetVal() TestEnumAlias {
	if x != nil {
		return x.Val
	}
	return TestEnumAlias_A
}

type EnumDefined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           TestEnum               `protobuf:"varint,1,opt,name=val,proto3,enum=tests.cases.TestEnum" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumDefined) Reset() {
	*x = EnumDefined{}
	mi := &file_cases_enums_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumDefined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumDefined) ProtoMessage() {}

func (x *EnumDefined) ProtoReflect() protoreflect.Message {
	mi := &file_cases_enums_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumDefined.ProtoReflect.Descriptor instead.
func (*EnumDefined) Descriptor() ([]byte, []int) {
	return file_cases_enums_proto_rawDescGZIP(), []int{3}
}

func (x *EnumDefined) GetVal() TestEnum {
	if x != nil {
		return x.Val
	}
	return TestEnum_ZERO
}

type EnumAliasDefined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           TestEnumAlias          `protobuf:"varint,1,opt,name=val,proto3,enum=tests.cases.TestEnumAlias" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumAliasDefined) Reset() {
	*x = EnumAliasDefined{}
	mi := &file_cases_enums_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumAliasDefined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumAliasDefined) ProtoMessage() {}

func (x *EnumAliasDefined) ProtoReflect() protoreflect.Message {
	mi := &file_cases_enums_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumAliasDefined.ProtoReflect.Descriptor instead.
func (*EnumAliasDefined) Descriptor() ([]byte, []int) {
	return file_cases_enums_proto_rawDescGZIP(), []int{4}
}

func (x *EnumAliasDefined) GetVal() TestEnumAlias {
	if x != nil {
		return x.Val
	}
	return TestEnumAlias_A
}

type EnumIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           TestEnum               `protobuf:"varint,1,opt,name=val,proto3,enum=tests.cases.TestEnum" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumIn) Reset() {
	*x = EnumIn{}
	mi := &file_cases_enums_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumIn) ProtoMessage() {}

func (x *EnumIn) ProtoReflect() protoreflect.Message {
	mi := &file_cases_enums_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumIn.ProtoReflect.Descriptor instead.
func (*EnumIn) Descriptor() ([]byte, []int) {
	return file_cases_enums_proto_rawDescGZIP(), []int{5}
}

func (x *EnumIn) GetVal() TestEnum {
	if x != nil {
		return x.Val
	}
	return TestEnum_ZERO
}

type EnumAliasIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           TestEnumAlias          `protobuf:"varint,1,opt,name=val,proto3,enum=tests.cases.TestEnumAlias" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumAliasIn) Reset() {
	*x = EnumAliasIn{}
	mi := &file_cases_enums_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumAliasIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumAliasIn) ProtoMessage() {}

func (x *EnumAliasIn) ProtoReflect() protoreflect.Message {
	mi := &file_cases_enums_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumAliasIn.ProtoReflect.Descriptor instead.
func (*EnumAliasIn) Descriptor() ([]byte, []int) {
	return file_cases_enums_proto_rawDescGZIP(), []int{6}
}

func (x *EnumAliasIn) GetVal() TestEnumAlias {
	if x != nil {
		return x.Val
	}
	return TestEnumAlias_A
}

type EnumNotIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           TestEnum               `protobuf:"varint,1,opt,name=val,proto3,enum=tests.cases.TestEnum" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumNotIn) Reset() {
	*x = EnumNotIn{}
	mi := &file_cases_enums_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumNotIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumNotIn) ProtoMessage() {}

func (x *EnumNotIn) ProtoReflect() protoreflect.Message {
	mi := &file_cases_enums_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumNotIn.ProtoReflect.Descriptor instead.
func (*EnumNotIn) Descriptor() ([]byte, []int) {
	return file_cases_enums_proto_rawDescGZIP(), []int{7}
}

func (x *EnumNotIn) GetVal() TestEnum {
	if x != nil {
		return x.Val
	}
	return TestEnum_ZERO
}

type EnumAliasNotIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           TestEnumAlias          `protobuf:"varint,1,opt,name=val,proto3,enum=tests.cases.TestEnumAlias" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumAliasNotIn) Reset() {
	*x = EnumAliasNotIn{}
	mi := &file_cases_enums_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumAliasNotIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumAliasNotIn) ProtoMessage() {}

func (x *EnumAliasNotIn) ProtoReflect() protoreflect.Message {
	mi := &file_cases_enums_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumAliasNotIn.ProtoReflect.Descriptor instead.
func (*EnumAliasNotIn) Descriptor() ([]byte, []int) {
	return file_cases_enums_proto_rawDescGZIP(), []int{8}
}

func (x *EnumAliasNotIn) GetVal() TestEnumAlias {
	if x != nil {
		return x.Val
	}
	return TestEnumAlias_A
}

type EnumExternal struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Val           other_package.Embed_Enumerated `protobuf:"varint,1,opt,name=val,proto3,enum=tests.cases.other_package.Embed_Enumerated" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumExternal) Reset() {
	*x = EnumExternal{}
	mi := &file_cases_enums_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumExternal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumExternal) ProtoMessage() {}

func (x *EnumExternal) ProtoReflect() protoreflect.Message {
	mi := &file_cases_enums_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumExternal.ProtoReflect.Descriptor instead.
func (*EnumExternal) Descriptor() ([]byte, []int) {
	return file_cases_enums_proto_rawDescGZIP(), []int{9}
}

func (x *EnumExternal) GetVal() other_package.Embed_Enumerated {
	if x != nil {
		return x.Val
	}
	return other_package.Embed_Enumerated(0)
}

type EnumExternal2 struct {
	state         protoimpl.MessageState                           `protogen:"open.v1"`
	Val           other_package.Embed_DoubleEmbed_DoubleEnumerated `protobuf:"varint,1,opt,name=val,proto3,enum=tests.cases.other_package.Embed_DoubleEmbed_DoubleEnumerated" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumExternal2) Reset() {
	*x = EnumExternal2{}
	mi := &file_cases_enums_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumExternal2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumExternal2) ProtoMessage() {}

func (x *EnumExternal2) ProtoReflect() protoreflect.Message {
	mi := &file_cases_enums_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumExternal2.ProtoReflect.Descriptor instead.
func (*EnumExternal2) Descriptor() ([]byte, []int) {
	return file_cases_enums_proto_rawDescGZIP(), []int{10}
}

func (x *EnumExternal2) GetVal() other_package.Embed_DoubleEmbed_DoubleEnumerated {
	if x != nil {
		return x.Val
	}
	return other_package.Embed_DoubleEmbed_DoubleEnumerated(0)
}

type EnumExternal3 struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Foo           other_package.Embed_FooNumber       `protobuf:"varint,1,opt,name=foo,proto3,enum=tests.cases.other_package.Embed_FooNumber" json:"foo,omitempty"`
	Bar           yet_another_package.Embed_BarNumber `protobuf:"varint,2,opt,name=bar,proto3,enum=tests.cases.yet_another_package.Embed_BarNumber" json:"bar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumExternal3) Reset() {
	*x = EnumExternal3{}
	mi := &file_cases_enums_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumExternal3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumExternal3) ProtoMessage() {}

func (x *EnumExternal3) ProtoReflect() protoreflect.Message {
	mi := &file_cases_enums_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumExternal3.ProtoReflect.Descriptor instead.
func (*EnumExternal3) Descriptor() ([]byte, []int) {
	return file_cases_enums_proto_rawDescGZIP(), []int{11}
}

func (x *EnumExternal3) GetFoo() other_package.Embed_FooNumber {
	if x != nil {
		return x.Foo
	}
	return other_package.Embed_FooNumber(0)
}

func (x *EnumExternal3) GetBar() yet_another_package.Embed_BarNumber {
	if x != nil {
		return x.Bar
	}
	return yet_another_package.Embed_BarNumber(0)
}

type EnumExternal4 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SortDirection sort.Direction         `protobuf:"varint,1,opt,name=sort_direction,json=sortDirection,proto3,enum=tests.cases.sort.Direction" json:"sort_direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumExternal4) Reset() {
	*x = EnumExternal4{}
	mi := &file_cases_enums_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumExternal4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumExternal4) ProtoMessage() {}

func (x *EnumExternal4) ProtoReflect() protoreflect.Message {
	mi := &file_cases_enums_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumExternal4.ProtoReflect.Descriptor instead.
func (*EnumExternal4) Descriptor() ([]byte, []int) {
	return file_cases_enums_proto_rawDescGZIP(), []int{12}
}

func (x *EnumExternal4) GetSortDirection() sort.Direction {
	if x != nil {
		return x.SortDirection
	}
	return sort.Direction(0)
}

type RepeatedEnumDefined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           []TestEnum             `protobuf:"varint,1,rep,packed,name=val,proto3,enum=tests.cases.TestEnum" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedEnumDefined) Reset() {
	*x = RepeatedEnumDefined{}
	mi := &file_cases_enums_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedEnumDefined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedEnumDefined) ProtoMessage() {}

func (x *RepeatedEnumDefined) ProtoReflect() protoreflect.Message {
	mi := &file_cases_enums_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedEnumDefined.ProtoReflect.Descriptor instead.
func (*RepeatedEnumDefined) Descriptor() ([]byte, []int) {
	return file_cases_enums_proto_rawDescGZIP(), []int{13}
}

func (x *RepeatedEnumDefined) GetVal() []TestEnum {
	if x != nil {
		return x.Val
	}
	return nil
}

type RepeatedExternalEnumDefined struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Val           []other_package.Embed_Enumerated `protobuf:"varint,1,rep,packed,name=val,proto3,enum=tests.cases.other_package.Embed_Enumerated" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedExternalEnumDefined) Reset() {
	*x = RepeatedExternalEnumDefined{}
	mi := &file_cases_enums_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedExternalEnumDefined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedExternalEnumDefined) ProtoMessage() {}

func (x *RepeatedExternalEnumDefined) ProtoReflect() protoreflect.Message {
	mi := &file_cases_enums_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedExternalEnumDefined.ProtoReflect.Descriptor instead.
func (*RepeatedExternalEnumDefined) Descriptor() ([]byte, []int) {
	return file_cases_enums_proto_rawDescGZIP(), []int{14}
}

func (x *RepeatedExternalEnumDefined) GetVal() []other_package.Embed_Enumerated {
	if x != nil {
		return x.Val
	}
	return nil
}

type RepeatedYetAnotherExternalEnumDefined struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Val           []yet_another_package.Embed_Enumerated `protobuf:"varint,1,rep,packed,name=val,proto3,enum=tests.cases.yet_another_package.Embed_Enumerated" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedYetAnotherExternalEnumDefined) Reset() {
	*x = RepeatedYetAnotherExternalEnumDefined{}
	mi := &file_cases_enums_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedYetAnotherExternalEnumDefined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedYetAnotherExternalEnumDefined) ProtoMessage() {}

func (x *RepeatedYetAnotherExternalEnumDefined) ProtoReflect() protoreflect.Message {
	mi := &file_cases_enums_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedYetAnotherExternalEnumDefined.ProtoReflect.Descriptor instead.
func (*RepeatedYetAnotherExternalEnumDefined) Descriptor() ([]byte, []int) {
	return file_cases_enums_proto_rawDescGZIP(), []int{15}
}

func (x *RepeatedYetAnotherExternalEnumDefined) GetVal() []yet_another_package.Embed_Enumerated {
	if x != nil {
		return x.Val
	}
	return nil
}

type RepeatedEnumExternal struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Foo           []other_package.Embed_FooNumber       `protobuf:"varint,1,rep,packed,name=foo,proto3,enum=tests.cases.other_package.Embed_FooNumber" json:"foo,omitempty"`
	Bar           []yet_another_package.Embed_BarNumber `protobuf:"varint,2,rep,packed,name=bar,proto3,enum=tests.cases.yet_another_package.Embed_BarNumber" json:"bar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedEnumExternal) Reset() {
	*x = RepeatedEnumExternal{}
	mi := &file_cases_enums_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedEnumExternal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedEnumExternal) ProtoMessage() {}

func (x *RepeatedEnumExternal) ProtoReflect() protoreflect.Message {
	mi := &file_cases_enums_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedEnumExternal.ProtoReflect.Descriptor instead.
func (*RepeatedEnumExternal) Descriptor() ([]byte, []int) {
	return file_cases_enums_proto_rawDescGZIP(), []int{16}
}

func (x *RepeatedEnumExternal) GetFoo() []other_package.Embed_FooNumber {
	if x != nil {
		return x.Foo
	}
	return nil
}

func (x *RepeatedEnumExternal) GetBar() []yet_another_package.Embed_BarNumber {
	if x != nil {
		return x.Bar
	}
	return nil
}

type MapEnumDefined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           map[string]TestEnum    `protobuf:"bytes,1,rep,name=val,proto3" json:"val,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=tests.cases.TestEnum"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapEnumDefined) Reset() {
	*x = MapEnumDefined{}
	mi := &file_cases_enums_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapEnumDefined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapEnumDefined) ProtoMessage() {}

func (x *MapEnumDefined) ProtoReflect() protoreflect.Message {
	mi := &file_cases_enums_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapEnumDefined.ProtoReflect.Descriptor instead.
func (*MapEnumDefined) Descriptor() ([]byte, []int) {
	return file_cases_enums_proto_rawDescGZIP(), []int{17}
}

func (x *MapEnumDefined) GetVal() map[string]TestEnum {
	if x != nil {
		return x.Val
	}
	return nil
}

type MapExternalEnumDefined struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	Val           map[string]other_package.Embed_Enumerated `protobuf:"bytes,1,rep,name=val,proto3" json:"val,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=tests.cases.other_package.Embed_Enumerated"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapExternalEnumDefined) Reset() {
	*x = MapExternalEnumDefined{}
	mi := &file_cases_enums_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapExternalEnumDefined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapExternalEnumDefined) ProtoMessage() {}

func (x *MapExternalEnumDefined) ProtoReflect() protoreflect.Message {
	mi := &file_cases_enums_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapExternalEnumDefined.ProtoReflect.Descriptor instead.
func (*MapExternalEnumDefined) Descriptor() ([]byte, []int) {
	return file_cases_enums_proto_rawDescGZIP(), []int{18}
}

func (x *MapExternalEnumDefined) GetVal() map[string]other_package.Embed_Enumerated {
	if x != nil {
		return x.Val
	}
	return nil
}

type EnumInsideOneOf struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Foo:
	//
	//	*EnumInsideOneOf_Val
	Foo isEnumInsideOneOf_Foo `protobuf_oneof:"foo"`
	// Types that are valid to be assigned to Bar:
	//
	//	*EnumInsideOneOf_Val21
	Bar           isEnumInsideOneOf_Bar `protobuf_oneof:"bar"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumInsideOneOf) Reset() {
	*x = EnumInsideOneOf{}
	mi := &file_cases_enums_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumInsideOneOf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumInsideOneOf) ProtoMessage() {}

func (x *EnumInsideOneOf) ProtoReflect() protoreflect.Message {
	mi := &file_cases_enums_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumInsideOneOf.ProtoReflect.Descriptor instead.
func (*EnumInsideOneOf) Descriptor() ([]byte, []int) {
	return file_cases_enums_proto_rawDescGZIP(), []int{19}
}

func (x *EnumInsideOneOf) GetFoo() isEnumInsideOneOf_Foo {
	if x != nil {
		return x.Foo
	}
	return nil
}

func (x *EnumInsideOneOf) GetVal() TestEnum {
	if x != nil {
		if x, ok := x.Foo.(*EnumInsideOneOf_Val); ok {
			return x.Val
		}
	}
	return TestEnum_ZERO
}

func (x *EnumInsideOneOf) GetBar() isEnumInsideOneOf_Bar {
	if x != nil {
		return x.Bar
	}
	return nil
}

func (x *EnumInsideOneOf) GetVal21() TestEnum {
	if x != nil {
		if x, ok := x.Bar.(*EnumInsideOneOf_Val21); ok {
			return x.Val21
		}
	}
	return TestEnum_ZERO
}

type isEnumInsideOneOf_Foo interface {
	isEnumInsideOneOf_Foo()
}

type EnumInsideOneOf_Val struct {
	Val TestEnum `protobuf:"varint,1,opt,name=val,proto3,enum=tests.cases.TestEnum,oneof"`
}

func (*EnumInsideOneOf_Val) isEnumInsideOneOf_Foo() {}

type isEnumInsideOneOf_Bar interface {
	isEnumInsideOneOf_Bar()
}

type EnumInsideOneOf_Val21 struct {
	Val21 TestEnum `protobuf:"varint,3,opt,name=val21,proto3,enum=tests.cases.TestEnum,oneof"`
}

func (*EnumInsideOneOf_Val21) isEnumInsideOneOf_Bar() {}

var File_cases_enums_proto protoreflect.FileDescriptor

const file_cases_enums_proto_rawDesc = "" +
	"\n" +
	"\x11cases/enums.proto\x12\vtests.cases\x1a\tv/v.proto\x1a\x1fcases/other_package/embed.proto\x1a%cases/yet_another_package/embed.proto\x1a\x15cases/sort/sort.proto\"3\n" +
	"\bEnumNone\x12'\n" +
	"\x03val\x18\x01 \x01(\x0e2\x15.tests.cases.TestEnumR\x03val\">\n" +
	"\tEnumConst\x121\n" +
	"\x03val\x18\x01 \x01(\x0e2\x15.tests.cases.TestEnumB\b\xa2Z\x05\x82\x01\x02\b\x02R\x03val\"H\n" +
	"\x0eEnumAliasConst\x126\n" +
	"\x03val\x18\x01 \x01(\x0e2\x1a.tests.cases.TestEnumAliasB\b\xa2Z\x05\x82\x01\x02\b\x02R\x03val\"@\n" +
	"\vEnumDefined\x121\n" +
	"\x03val\x18\x01 \x01(\x0e2\x15.tests.cases.TestEnumB\b\xa2Z\x05\x82\x01\x02\x10\x01R\x03val\"J\n" +
	"\x10EnumAliasDefined\x126\n" +
	"\x03val\x18\x01 \x01(\x0e2\x1a.tests.cases.TestEnumAliasB\b\xa2Z\x05\x82\x01\x02\x10\x01R\x03val\"=\n" +
	"\x06EnumIn\x123\n" +
	"\x03val\x18\x01 \x01(\x0e2\x15.tests.cases.TestEnumB\n" +
	"\xa2Z\a\x82\x01\x04\x1a\x02\x00\x02R\x03val\"G\n" +
	"\vEnumAliasIn\x128\n" +
	"\x03val\x18\x01 \x01(\x0e2\x1a.tests.cases.TestEnumAliasB\n" +
	"\xa2Z\a\x82\x01\x04\x1a\x02\x00\x02R\x03val\"?\n" +
	"\tEnumNotIn\x122\n" +
	"\x03val\x18\x01 \x01(\x0e2\x15.tests.cases.TestEnumB\t\xa2Z\x06\x82\x01\x03\"\x01\x01R\x03val\"I\n" +
	"\x0eEnumAliasNotIn\x127\n" +
	"\x03val\x18\x01 \x01(\x0e2\x1a.tests.cases.TestEnumAliasB\t\xa2Z\x06\x82\x01\x03\"\x01\x01R\x03val\"W\n" +
	"\fEnumExternal\x12G\n" +
	"\x03val\x18\x01 \x01(\x0e2+.tests.cases.other_package.Embed.EnumeratedB\b\xa2Z\x05\x82\x01\x02\x10\x01R\x03val\"j\n" +
	"\rEnumExternal2\x12Y\n" +
	"\x03val\x18\x01 \x01(\x0e2=.tests.cases.other_package.Embed.DoubleEmbed.DoubleEnumeratedB\b\xa2Z\x05\x82\x01\x02\x10\x01R\x03val\"\xa8\x01\n" +
	"\rEnumExternal3\x12H\n" +
	"\x03foo\x18\x01 \x01(\x0e2*.tests.cases.other_package.Embed.FooNumberB\n" +
	"\xa2Z\a\x82\x01\x04\x1a\x02\x00\x02R\x03foo\x12M\n" +
	"\x03bar\x18\x02 \x01(\x0e20.tests.cases.yet_another_package.Embed.BarNumberB\t\xa2Z\x06\x82\x01\x03\"\x01\x01R\x03bar\"]\n" +
	"\rEnumExternal4\x12L\n" +
	"\x0esort_direction\x18\x01 \x01(\x0e2\x1b.tests.cases.sort.DirectionB\b\xa2Z\x05\x82\x01\x02\b\x01R\rsortDirection\"M\n" +
	"\x13RepeatedEnumDefined\x126\n" +
	"\x03val\x18\x01 \x03(\x0e2\x15.tests.cases.TestEnumB\r\xa2Z\n" +
	"\x92\x01\a\"\x05\x82\x01\x02\x10\x01R\x03val\"k\n" +
	"\x1bRepeatedExternalEnumDefined\x12L\n" +
	"\x03val\x18\x01 \x03(\x0e2+.tests.cases.other_package.Embed.EnumeratedB\r\xa2Z\n" +
	"\x92\x01\a\"\x05\x82\x01\x02\x10\x01R\x03val\"{\n" +
	"%RepeatedYetAnotherExternalEnumDefined\x12R\n" +
	"\x03val\x18\x01 \x03(\x0e21.tests.cases.yet_another_package.Embed.EnumeratedB\r\xa2Z\n" +
	"\x92\x01\a\"\x05\x82\x01\x02\x10\x01R\x03val\"\xb9\x01\n" +
	"\x14RepeatedEnumExternal\x12M\n" +
	"\x03foo\x18\x01 \x03(\x0e2*.tests.cases.other_package.Embed.FooNumberB\x0f\xa2Z\f\x92\x01\t\"\a\x82\x01\x04\x1a\x02\x00\x02R\x03foo\x12R\n" +
	"\x03bar\x18\x02 \x03(\x0e20.tests.cases.yet_another_package.Embed.BarNumberB\x0e\xa2Z\v\x92\x01\b\"\x06\x82\x01\x03\"\x01\x01R\x03bar\"\xa6\x01\n" +
	"\x0eMapEnumDefined\x12E\n" +
	"\x03val\x18\x01 \x03(\v2$.tests.cases.MapEnumDefined.ValEntryB\r\xa2Z\n" +
	"\x9a\x01\a*\x05\x82\x01\x02\x10\x01R\x03val\x1aM\n" +
	"\bValEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\x0e2\x15.tests.cases.TestEnumR\x05value:\x028\x01\"\xcc\x01\n" +
	"\x16MapExternalEnumDefined\x12M\n" +
	"\x03val\x18\x01 \x03(\v2,.tests.cases.MapExternalEnumDefined.ValEntryB\r\xa2Z\n" +
	"\x9a\x01\a*\x05\x82\x01\x02\x10\x01R\x03val\x1ac\n" +
	"\bValEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12A\n" +
	"\x05value\x18\x02 \x01(\x0e2+.tests.cases.other_package.Embed.EnumeratedR\x05value:\x028\x01\"\x90\x01\n" +
	"\x0fEnumInsideOneOf\x123\n" +
	"\x03val\x18\x01 \x01(\x0e2\x15.tests.cases.TestEnumB\b\xa2Z\x05\x82\x01\x02\x10\x01H\x00R\x03val\x12:\n" +
	"\x05val21\x18\x03 \x01(\x0e2\x15.tests.cases.TestEnumB\v\xa2Z\b\x82\x01\x05\x10\x01\"\x01\x00H\x01R\x05val21B\x05\n" +
	"\x03fooB\x05\n" +
	"\x03bar*&\n" +
	"\bTestEnum\x12\b\n" +
	"\x04ZERO\x10\x00\x12\a\n" +
	"\x03ONE\x10\x01\x12\a\n" +
	"\x03TWO\x10\x02*H\n" +
	"\rTestEnumAlias\x12\x05\n" +
	"\x01A\x10\x00\x12\x05\n" +
	"\x01B\x10\x01\x12\x05\n" +
	"\x01C\x10\x02\x12\t\n" +
	"\x05ALPHA\x10\x00\x12\b\n" +
	"\x04BETA\x10\x01\x12\t\n" +
	"\x05GAMMA\x10\x02\x1a\x02\x10\x01BGZEgithub.com/ml444/gkit/cmd/protoc-gen-go-validate/tests/cases/go;casesb\x06proto3"

var (
	file_cases_enums_proto_rawDescOnce sync.Once
	file_cases_enums_proto_rawDescData []byte
)

func file_cases_enums_proto_rawDescGZIP() []byte {
	file_cases_enums_proto_rawDescOnce.Do(func() {
		file_cases_enums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cases_enums_proto_rawDesc), len(file_cases_enums_proto_rawDesc)))
	})
	return file_cases_enums_proto_rawDescData
}

var file_cases_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cases_enums_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_cases_enums_proto_goTypes = []any{
	(TestEnum)(0),                                 // 0: tests.cases.TestEnum
	(TestEnumAlias)(0),                            // 1: tests.cases.TestEnumAlias
	(*EnumNone)(nil),                              // 2: tests.cases.EnumNone
	(*EnumConst)(nil),                             // 3: tests.cases.EnumConst
	(*EnumAliasConst)(nil),                        // 4: tests.cases.EnumAliasConst
	(*EnumDefined)(nil),                           // 5: tests.cases.EnumDefined
	(*EnumAliasDefined)(nil),                      // 6: tests.cases.EnumAliasDefined
	(*EnumIn)(nil),                                // 7: tests.cases.EnumIn
	(*EnumAliasIn)(nil),                           // 8: tests.cases.EnumAliasIn
	(*EnumNotIn)(nil),                             // 9: tests.cases.EnumNotIn
	(*EnumAliasNotIn)(nil),                        // 10: tests.cases.EnumAliasNotIn
	(*EnumExternal)(nil),                          // 11: tests.cases.EnumExternal
	(*EnumExternal2)(nil),                         // 12: tests.cases.EnumExternal2
	(*EnumExternal3)(nil),                         // 13: tests.cases.EnumExternal3
	(*EnumExternal4)(nil),                         // 14: tests.cases.EnumExternal4
	(*RepeatedEnumDefined)(nil),                   // 15: tests.cases.RepeatedEnumDefined
	(*RepeatedExternalEnumDefined)(nil),           // 16: tests.cases.RepeatedExternalEnumDefined
	(*RepeatedYetAnotherExternalEnumDefined)(nil), // 17: tests.cases.RepeatedYetAnotherExternalEnumDefined
	(*RepeatedEnumExternal)(nil),                  // 18: tests.cases.RepeatedEnumExternal
	(*MapEnumDefined)(nil),                        // 19: tests.cases.MapEnumDefined
	(*MapExternalEnumDefined)(nil),                // 20: tests.cases.MapExternalEnumDefined
	(*EnumInsideOneOf)(nil),                       // 21: tests.cases.EnumInsideOneOf
	nil,                                           // 22: tests.cases.MapEnumDefined.ValEntry
	nil,                                           // 23: tests.cases.MapExternalEnumDefined.ValEntry
	(other_package.Embed_Enumerated)(0),           // 24: tests.cases.other_package.Embed.Enumerated
	(other_package.Embed_DoubleEmbed_DoubleEnumerated)(0), // 25: tests.cases.other_package.Embed.DoubleEmbed.DoubleEnumerated
	(other_package.Embed_FooNumber)(0),                    // 26: tests.cases.other_package.Embed.FooNumber
	(yet_another_package.Embed_BarNumber)(0),              // 27: tests.cases.yet_another_package.Embed.BarNumber
	(sort.Direction)(0),                                   // 28: tests.cases.sort.Direction
	(yet_another_package.Embed_Enumerated)(0),             // 29: tests.cases.yet_another_package.Embed.Enumerated
}
var file_cases_enums_proto_depIdxs = []int32{
	0,  // 0: tests.cases.EnumNone.val:type_name -> tests.cases.TestEnum
	0,  // 1: tests.cases.EnumConst.val:type_name -> tests.cases.TestEnum
	1,  // 2: tests.cases.EnumAliasConst.val:type_name -> tests.cases.TestEnumAlias
	0,  // 3: tests.cases.EnumDefined.val:type_name -> tests.cases.TestEnum
	1,  // 4: tests.cases.EnumAliasDefined.val:type_name -> tests.cases.TestEnumAlias
	0,  // 5: tests.cases.EnumIn.val:type_name -> tests.cases.TestEnum
	1,  // 6: tests.cases.EnumAliasIn.val:type_name -> tests.cases.TestEnumAlias
	0,  // 7: tests.cases.EnumNotIn.val:type_name -> tests.cases.TestEnum
	1,  // 8: tests.cases.EnumAliasNotIn.val:type_name -> tests.cases.TestEnumAlias
	24, // 9: tests.cases.EnumExternal.val:type_name -> tests.cases.other_package.Embed.Enumerated
	25, // 10: tests.cases.EnumExternal2.val:type_name -> tests.cases.other_package.Embed.DoubleEmbed.DoubleEnumerated
	26, // 11: tests.cases.EnumExternal3.foo:type_name -> tests.cases.other_package.Embed.FooNumber
	27, // 12: tests.cases.EnumExternal3.bar:type_name -> tests.cases.yet_another_package.Embed.BarNumber
	28, // 13: tests.cases.EnumExternal4.sort_direction:type_name -> tests.cases.sort.Direction
	0,  // 14: tests.cases.RepeatedEnumDefined.val:type_name -> tests.cases.TestEnum
	24, // 15: tests.cases.RepeatedExternalEnumDefined.val:type_name -> tests.cases.other_package.Embed.Enumerated
	29, // 16: tests.cases.RepeatedYetAnotherExternalEnumDefined.val:type_name -> tests.cases.yet_another_package.Embed.Enumerated
	26, // 17: tests.cases.RepeatedEnumExternal.foo:type_name -> tests.cases.other_package.Embed.FooNumber
	27, // 18: tests.cases.RepeatedEnumExternal.bar:type_name -> tests.cases.yet_another_package.Embed.BarNumber
	22, // 19: tests.cases.MapEnumDefined.val:type_name -> tests.cases.MapEnumDefined.ValEntry
	23, // 20: tests.cases.MapExternalEnumDefined.val:type_name -> tests.cases.MapExternalEnumDefined.ValEntry
	0,  // 21: tests.cases.EnumInsideOneOf.val:type_name -> tests.cases.TestEnum
	0,  // 22: tests.cases.EnumInsideOneOf.val21:type_name -> tests.cases.TestEnum
	0,  // 23: tests.cases.MapEnumDefined.ValEntry.value:type_name -> tests.cases.TestEnum
	24, // 24: tests.cases.MapExternalEnumDefined.ValEntry.value:type_name -> tests.cases.other_package.Embed.Enumerated
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_cases_enums_proto_init() }
func file_cases_enums_proto_init() {
	if File_cases_enums_proto != nil {
		return
	}
	file_cases_enums_proto_msgTypes[19].OneofWrappers = []any{
		(*EnumInsideOneOf_Val)(nil),
		(*EnumInsideOneOf_Val21)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cases_enums_proto_rawDesc), len(file_cases_enums_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cases_enums_proto_goTypes,
		DependencyIndexes: file_cases_enums_proto_depIdxs,
		EnumInfos:         file_cases_enums_proto_enumTypes,
		MessageInfos:      file_cases_enums_proto_msgTypes,
	}.Build()
	File_cases_enums_proto = out.File
	file_cases_enums_proto_goTypes = nil
	file_cases_enums_proto_depIdxs = nil
}
