// Code generated by protoc-gen-go-validate. DO NOT EDIT.
// - protoc-gen-go-validate 1.0.0
// - protoc             v6.30.2
// source: cases/enums.proto

package cases

import (
	"errors"
	"fmt"
	"regexp"
	"sort"
	"strings"

	other_package5 "github.com/ml444/gkit/cmd/protoc-gen-go-validate/tests/cases/other_package"
	yet_another_package3 "github.com/ml444/gkit/cmd/protoc-gen-go-validate/tests/cases/yet_another_package"

	"github.com/ml444/gkit/errorx"
)

// ensure the imports are used
var (
	_ = errors.New("")
	_ = fmt.Print
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = sort.Sort
)

func enumsValidationError(errCode int32, msg string, cause error) error {
	err := errorx.CreateError(400, errCode, msg)
	if cause != nil {
		err = err.WithCause(cause)
	}
	return err
}

// enumsMultiError is an error wrapping multiple validation errors
// returned by .ValidateAll() if the designated constraints aren't met.
type enumsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m enumsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m enumsMultiError) AllErrors() []error { return m }

func (m *EnumConst) Validate() error {
	return m.validate(false)
}

func (m *EnumConst) ValidateAll() error {
	return m.validate(true)
}

func (m *EnumConst) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	if m.GetVal() != 2 {
		err := enumsValidationError(
			0,
			"[Val] value must equal TWO",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return enumsMultiError(errors)
	}
	return nil
}

func (m *EnumAliasConst) Validate() error {
	return m.validate(false)
}

func (m *EnumAliasConst) ValidateAll() error {
	return m.validate(true)
}

func (m *EnumAliasConst) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	if m.GetVal() != 2 {
		err := enumsValidationError(
			0,
			"[Val] value must equal C",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return enumsMultiError(errors)
	}
	return nil
}

func (m *EnumDefined) Validate() error {
	return m.validate(false)
}

func (m *EnumDefined) ValidateAll() error {
	return m.validate(true)
}

func (m *EnumDefined) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if _, ok := TestEnum_name[int32(m.GetVal())]; !ok {
		err := enumsValidationError(
			0,
			"[Val] value must be one of the defined enum values",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return enumsMultiError(errors)
	}
	return nil
}

func (m *EnumAliasDefined) Validate() error {
	return m.validate(false)
}

func (m *EnumAliasDefined) ValidateAll() error {
	return m.validate(true)
}

func (m *EnumAliasDefined) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if _, ok := TestEnumAlias_name[int32(m.GetVal())]; !ok {
		err := enumsValidationError(
			0,
			"[Val] value must be one of the defined enum values",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return enumsMultiError(errors)
	}
	return nil
}

func (m *EnumIn) Validate() error {
	return m.validate(false)
}

func (m *EnumIn) ValidateAll() error {
	return m.validate(true)
}

func (m *EnumIn) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if _, ok := _EnumIn_Val_InLookup[m.GetVal()]; !ok {
		err := enumsValidationError(
			0,
			"[Val] value must be in [ZERO TWO]",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return enumsMultiError(errors)
	}
	return nil
}

var _EnumIn_Val_InLookup = map[TestEnum]struct{}{
	0: {},
	2: {},
}

func (m *EnumAliasIn) Validate() error {
	return m.validate(false)
}

func (m *EnumAliasIn) ValidateAll() error {
	return m.validate(true)
}

func (m *EnumAliasIn) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if _, ok := _EnumAliasIn_Val_InLookup[m.GetVal()]; !ok {
		err := enumsValidationError(
			0,
			"[Val] value must be in [A C]",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return enumsMultiError(errors)
	}
	return nil
}

var _EnumAliasIn_Val_InLookup = map[TestEnumAlias]struct{}{
	0: {},
	2: {},
}

func (m *EnumNotIn) Validate() error {
	return m.validate(false)
}

func (m *EnumNotIn) ValidateAll() error {
	return m.validate(true)
}

func (m *EnumNotIn) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if _, ok := _EnumNotIn_Val_NotInLookup[m.GetVal()]; ok {
		err := enumsValidationError(
			0,
			"[Val] value must not be in [ONE]",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return enumsMultiError(errors)
	}
	return nil
}

var _EnumNotIn_Val_NotInLookup = map[TestEnum]struct{}{
	1: {},
}

func (m *EnumAliasNotIn) Validate() error {
	return m.validate(false)
}

func (m *EnumAliasNotIn) ValidateAll() error {
	return m.validate(true)
}

func (m *EnumAliasNotIn) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if _, ok := _EnumAliasNotIn_Val_NotInLookup[m.GetVal()]; ok {
		err := enumsValidationError(
			0,
			"[Val] value must not be in [B]",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return enumsMultiError(errors)
	}
	return nil
}

var _EnumAliasNotIn_Val_NotInLookup = map[TestEnumAlias]struct{}{
	1: {},
}

func (m *EnumExternal) Validate() error {
	return m.validate(false)
}

func (m *EnumExternal) ValidateAll() error {
	return m.validate(true)
}

func (m *EnumExternal) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if _, ok := other_package5.Embed_Enumerated_name[int32(m.GetVal())]; !ok {
		err := enumsValidationError(
			0,
			"[Val] value must be one of the defined enum values",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return enumsMultiError(errors)
	}
	return nil
}

func (m *EnumExternal2) Validate() error {
	return m.validate(false)
}

func (m *EnumExternal2) ValidateAll() error {
	return m.validate(true)
}

func (m *EnumExternal2) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if _, ok := other_package5.Embed_DoubleEmbed_DoubleEnumerated_name[int32(m.GetVal())]; !ok {
		err := enumsValidationError(
			0,
			"[Val] value must be one of the defined enum values",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return enumsMultiError(errors)
	}
	return nil
}

func (m *EnumExternal3) Validate() error {
	return m.validate(false)
}

func (m *EnumExternal3) ValidateAll() error {
	return m.validate(true)
}

func (m *EnumExternal3) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if _, ok := _EnumExternal3_Foo_InLookup[m.GetFoo()]; !ok {
		err := enumsValidationError(
			0,
			"[Foo] value must be in [ZERO TWO]",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _EnumExternal3_Bar_NotInLookup[m.GetBar()]; ok {
		err := enumsValidationError(
			0,
			"[Bar] value must not be in [ONE]",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return enumsMultiError(errors)
	}
	return nil
}

var _EnumExternal3_Foo_InLookup = map[other_package5.Embed_FooNumber]struct{}{
	0: {},
	2: {},
}
var _EnumExternal3_Bar_NotInLookup = map[yet_another_package3.Embed_BarNumber]struct{}{
	1: {},
}

func (m *EnumExternal4) Validate() error {
	return m.validate(false)
}

func (m *EnumExternal4) ValidateAll() error {
	return m.validate(true)
}

func (m *EnumExternal4) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	if m.GetSortDirection() != 1 {
		err := enumsValidationError(
			0,
			"[SortDirection] value must equal ASC",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return enumsMultiError(errors)
	}
	return nil
}

func (m *RepeatedEnumDefined) Validate() error {
	return m.validate(false)
}

func (m *RepeatedEnumDefined) ValidateAll() error {
	return m.validate(true)
}

func (m *RepeatedEnumDefined) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	for idx, item := range m.GetVal() {
		_, _ = idx, item

		if _, ok := TestEnum_name[int32(item)]; !ok {
			err := enumsValidationError(
				0,
				"[Val] value must be one of the defined enum values",
				nil,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return enumsMultiError(errors)
	}
	return nil
}

func (m *RepeatedExternalEnumDefined) Validate() error {
	return m.validate(false)
}

func (m *RepeatedExternalEnumDefined) ValidateAll() error {
	return m.validate(true)
}

func (m *RepeatedExternalEnumDefined) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	for idx, item := range m.GetVal() {
		_, _ = idx, item

		if _, ok := other_package5.Embed_Enumerated_name[int32(item)]; !ok {
			err := enumsValidationError(
				0,
				"[Val] value must be one of the defined enum values",
				nil,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return enumsMultiError(errors)
	}
	return nil
}

func (m *RepeatedYetAnotherExternalEnumDefined) Validate() error {
	return m.validate(false)
}

func (m *RepeatedYetAnotherExternalEnumDefined) ValidateAll() error {
	return m.validate(true)
}

func (m *RepeatedYetAnotherExternalEnumDefined) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	for idx, item := range m.GetVal() {
		_, _ = idx, item

		if _, ok := yet_another_package3.Embed_Enumerated_name[int32(item)]; !ok {
			err := enumsValidationError(
				0,
				"[Val] value must be one of the defined enum values",
				nil,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return enumsMultiError(errors)
	}
	return nil
}

func (m *RepeatedEnumExternal) Validate() error {
	return m.validate(false)
}

func (m *RepeatedEnumExternal) ValidateAll() error {
	return m.validate(true)
}

func (m *RepeatedEnumExternal) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	for idx, item := range m.GetFoo() {
		_, _ = idx, item

		if _, ok := _RepeatedEnumExternal_Foo_InLookup[item]; !ok {
			err := enumsValidationError(
				0,
				"[Foo] value must be in [ZERO TWO]",
				nil,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	for idx, item := range m.GetBar() {
		_, _ = idx, item

		if _, ok := _RepeatedEnumExternal_Bar_NotInLookup[item]; ok {
			err := enumsValidationError(
				0,
				"[Bar] value must not be in [ONE]",
				nil,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return enumsMultiError(errors)
	}
	return nil
}

var _RepeatedEnumExternal_Foo_InLookup = map[other_package5.Embed_FooNumber]struct{}{
	0: {},
	2: {},
}
var _RepeatedEnumExternal_Bar_NotInLookup = map[yet_another_package3.Embed_BarNumber]struct{}{
	1: {},
}

func (m *MapEnumDefined) Validate() error {
	return m.validate(false)
}

func (m *MapEnumDefined) ValidateAll() error {
	return m.validate(true)
}

func (m *MapEnumDefined) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	{
		if all {
			sorted_keys := make([]string, len(m.GetVal()))
			i := 0
			for key := range m.GetVal() {
				sorted_keys[i] = key
				i++
			}
			sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
			for _, key := range sorted_keys {
				val := m.GetVal()[key]
				_ = val

				// no validation rules for Val

				if _, ok := TestEnum_name[int32(val)]; !ok {
					err := enumsValidationError(
						0,
						"[Val] value must be one of the defined enum values",
						nil,
					)
					if !all {
						return err
					}
					errors = append(errors, err)
				}

			}
		} else {
			for key, val := range m.GetVal() {
				_, _ = key, val

				// no validation rules for Val

				if _, ok := TestEnum_name[int32(val)]; !ok {
					err := enumsValidationError(
						0,
						"[Val] value must be one of the defined enum values",
						nil,
					)
					if !all {
						return err
					}
					errors = append(errors, err)
				}

			}
		}
	}

	if len(errors) > 0 {
		return enumsMultiError(errors)
	}
	return nil
}

func (m *MapExternalEnumDefined) Validate() error {
	return m.validate(false)
}

func (m *MapExternalEnumDefined) ValidateAll() error {
	return m.validate(true)
}

func (m *MapExternalEnumDefined) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	{
		if all {
			sorted_keys := make([]string, len(m.GetVal()))
			i := 0
			for key := range m.GetVal() {
				sorted_keys[i] = key
				i++
			}
			sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
			for _, key := range sorted_keys {
				val := m.GetVal()[key]
				_ = val

				// no validation rules for Val

				if _, ok := other_package5.Embed_Enumerated_name[int32(val)]; !ok {
					err := enumsValidationError(
						0,
						"[Val] value must be one of the defined enum values",
						nil,
					)
					if !all {
						return err
					}
					errors = append(errors, err)
				}

			}
		} else {
			for key, val := range m.GetVal() {
				_, _ = key, val

				// no validation rules for Val

				if _, ok := other_package5.Embed_Enumerated_name[int32(val)]; !ok {
					err := enumsValidationError(
						0,
						"[Val] value must be one of the defined enum values",
						nil,
					)
					if !all {
						return err
					}
					errors = append(errors, err)
				}

			}
		}
	}

	if len(errors) > 0 {
		return enumsMultiError(errors)
	}
	return nil
}

func (m *EnumInsideOneOf) Validate() error {
	return m.validate(false)
}

func (m *EnumInsideOneOf) ValidateAll() error {
	return m.validate(true)
}

func (m *EnumInsideOneOf) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	switch v := m.Bar.(type) {
	case *EnumInsideOneOf_Val21:
		if v == nil {
			err := enumsValidationError(
				0,
				"[Bar] oneof value cannot be a typed-nil",
				nil,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if _, ok := _EnumInsideOneOf_Val21_NotInLookup[m.GetVal21()]; ok {
			err := enumsValidationError(
				0,
				"[Val21] value must not be in [ZERO]",
				nil,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if _, ok := TestEnum_name[int32(m.GetVal21())]; !ok {
			err := enumsValidationError(
				0,
				"[Val21] value must be one of the defined enum values",
				nil,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	default:
		_ = v // ensures v is used
	}
	switch v := m.Foo.(type) {
	case *EnumInsideOneOf_Val:
		if v == nil {
			err := enumsValidationError(
				0,
				"[Foo] oneof value cannot be a typed-nil",
				nil,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if _, ok := TestEnum_name[int32(m.GetVal())]; !ok {
			err := enumsValidationError(
				0,
				"[Val] value must be one of the defined enum values",
				nil,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return enumsMultiError(errors)
	}
	return nil
}

var _EnumInsideOneOf_Val21_NotInLookup = map[TestEnum]struct{}{
	0: {},
}
