// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: cases/filename-with-dash.proto

package cases

import (
	reflect "reflect"
	unsafe "unsafe"

	_ "github.com/ml444/gkit/cmd/protoc-gen-go-validate/v"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_cases_filename_with_dash_proto protoreflect.FileDescriptor

const file_cases_filename_with_dash_proto_rawDesc = "" +
	"\n" +
	"\x1ecases/filename-with-dash.proto\x12\vtests.cases\x1a\tv/v.protoBGZEgithub.com/ml444/gkit/cmd/protoc-gen-go-validate/tests/cases/go;casesb\x06proto3"

var file_cases_filename_with_dash_proto_goTypes = []any{}
var file_cases_filename_with_dash_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cases_filename_with_dash_proto_init() }
func file_cases_filename_with_dash_proto_init() {
	if File_cases_filename_with_dash_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cases_filename_with_dash_proto_rawDesc), len(file_cases_filename_with_dash_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cases_filename_with_dash_proto_goTypes,
		DependencyIndexes: file_cases_filename_with_dash_proto_depIdxs,
	}.Build()
	File_cases_filename_with_dash_proto = out.File
	file_cases_filename_with_dash_proto_goTypes = nil
	file_cases_filename_with_dash_proto_depIdxs = nil
}
