// Code generated by protoc-gen-go-validate. DO NOT EDIT.
// - protoc-gen-go-validate 1.0.0
// - protoc             v6.30.2
// source: cases/maps.proto

package cases

import (
	"errors"
	"fmt"
	"regexp"
	"sort"
	"strings"
	"unicode/utf8"

	"github.com/ml444/gkit/errorx"
)

// ensure the imports are used
var (
	_ = errors.New("")
	_ = fmt.Print
	_ = (*strings.Reader)(nil)
	_ = sort.Sort
)

func mapsValidationError(errCode int32, msg string, cause error) error {
	err := errorx.CreateError(400, errCode, msg)
	if cause != nil {
		err = err.WithCause(cause)
	}
	return err
}

// mapsMultiError is an error wrapping multiple validation errors
// returned by .ValidateAll() if the designated constraints aren't met.
type mapsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m mapsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m mapsMultiError) AllErrors() []error { return m }

func (m *MapMin) Validate() error {
	return m.validate(false)
}

func (m *MapMin) ValidateAll() error {
	return m.validate(true)
}

func (m *MapMin) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if len(m.GetVal()) < 2 {
		err := mapsValidationError(
			0,
			"[Val] value must contain at least 2 pair(s)",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return mapsMultiError(errors)
	}
	return nil
}

func (m *MapMax) Validate() error {
	return m.validate(false)
}

func (m *MapMax) ValidateAll() error {
	return m.validate(true)
}

func (m *MapMax) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if len(m.GetVal()) > 3 {
		err := mapsValidationError(
			0,
			"[Val] value must contain no more than 3 pair(s)",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return mapsMultiError(errors)
	}
	return nil
}

func (m *MapMinMax) Validate() error {
	return m.validate(false)
}

func (m *MapMinMax) ValidateAll() error {
	return m.validate(true)
}

func (m *MapMinMax) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if l := len(m.GetVal()); l < 2 || l > 4 {
		err := mapsValidationError(
			0,
			"[Val] value must contain between 2 and 4 pairs, inclusive",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return mapsMultiError(errors)
	}
	return nil
}

func (m *MapExact) Validate() error {
	return m.validate(false)
}

func (m *MapExact) ValidateAll() error {
	return m.validate(true)
}

func (m *MapExact) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if len(m.GetVal()) != 3 {
		err := mapsValidationError(
			0,
			"[Val] value must contain exactly 3 pair(s)",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return mapsMultiError(errors)
	}
	return nil
}

func (m *MapNoSparse) Validate() error {
	return m.validate(false)
}

func (m *MapNoSparse) ValidateAll() error {
	return m.validate(true)
}

func (m *MapNoSparse) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	{
		if all {
			sorted_keys := make([]uint32, len(m.GetVal()))
			i := 0
			for key := range m.GetVal() {
				sorted_keys[i] = key
				i++
			}
			sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
			for _, key := range sorted_keys {
				val := m.GetVal()[key]
				_ = val

				if val == nil {
					err := mapsValidationError(
						0,
						fmt.Sprintf("[Val] key:%v value cannot be sparse, all pairs must be non-nil", key),
						nil,
					)
					if !all {
						return err
					}
					errors = append(errors, err)
				} // no validation rules for Val

				if all {
					switch v := interface{}(val).(type) {
					case interface{ ValidateAll() error }:
						if err := v.ValidateAll(); err != nil {
							errors = append(errors, mapsValidationError(
								0,
								"embedded message failed validation",
								err,
							))
						}
					case interface{ Validate() error }:
						if err := v.Validate(); err != nil {
							errors = append(errors, mapsValidationError(
								0,
								"embedded message failed validation",
								err,
							))
						}
					}
				} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
					if err := v.Validate(); err != nil {
						return mapsValidationError(
							0,
							"embedded message failed validation",
							err,
						)
					}
				}

			}
		} else {
			for key, val := range m.GetVal() {
				_, _ = key, val

				if val == nil {
					err := mapsValidationError(
						0,
						fmt.Sprintf("[Val] key:%v value cannot be sparse, all pairs must be non-nil", key),
						nil,
					)
					if !all {
						return err
					}
					errors = append(errors, err)
				} // no validation rules for Val

				if all {
					switch v := interface{}(val).(type) {
					case interface{ ValidateAll() error }:
						if err := v.ValidateAll(); err != nil {
							errors = append(errors, mapsValidationError(
								0,
								"embedded message failed validation",
								err,
							))
						}
					case interface{ Validate() error }:
						if err := v.Validate(); err != nil {
							errors = append(errors, mapsValidationError(
								0,
								"embedded message failed validation",
								err,
							))
						}
					}
				} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
					if err := v.Validate(); err != nil {
						return mapsValidationError(
							0,
							"embedded message failed validation",
							err,
						)
					}
				}

			}
		}
	}

	if len(errors) > 0 {
		return mapsMultiError(errors)
	}
	return nil
}

func (m *MapKeys) Validate() error {
	return m.validate(false)
}

func (m *MapKeys) ValidateAll() error {
	return m.validate(true)
}

func (m *MapKeys) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	{
		if all {
			sorted_keys := make([]int64, len(m.GetVal()))
			i := 0
			for key := range m.GetVal() {
				sorted_keys[i] = key
				i++
			}
			sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
			for _, key := range sorted_keys {
				val := m.GetVal()[key]
				_ = val

				if key >= 0 {
					err := mapsValidationError(
						0,
						"[Val] value must be less than 0",
						nil,
					)
					if !all {
						return err
					}
					errors = append(errors, err)
				}

				// no validation rules for Val

			}
		} else {
			for key, val := range m.GetVal() {
				_, _ = key, val

				if key >= 0 {
					err := mapsValidationError(
						0,
						"[Val] value must be less than 0",
						nil,
					)
					if !all {
						return err
					}
					errors = append(errors, err)
				}

				// no validation rules for Val

			}
		}
	}

	if len(errors) > 0 {
		return mapsMultiError(errors)
	}
	return nil
}

func (m *MapValues) Validate() error {
	return m.validate(false)
}

func (m *MapValues) ValidateAll() error {
	return m.validate(true)
}

func (m *MapValues) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	{
		if all {
			sorted_keys := make([]string, len(m.GetVal()))
			i := 0
			for key := range m.GetVal() {
				sorted_keys[i] = key
				i++
			}
			sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
			for _, key := range sorted_keys {
				val := m.GetVal()[key]
				_ = val

				// no validation rules for Val

				if utf8.RuneCountInString(val) < 3 {
					err := mapsValidationError(
						0,
						"[Val] value length must be at least 3 runes",
						nil,
					)
					if !all {
						return err
					}
					errors = append(errors, err)
				}

			}
		} else {
			for key, val := range m.GetVal() {
				_, _ = key, val

				// no validation rules for Val

				if utf8.RuneCountInString(val) < 3 {
					err := mapsValidationError(
						0,
						"[Val] value length must be at least 3 runes",
						nil,
					)
					if !all {
						return err
					}
					errors = append(errors, err)
				}

			}
		}
	}

	if len(errors) > 0 {
		return mapsMultiError(errors)
	}
	return nil
}

func (m *MapKeysPattern) Validate() error {
	return m.validate(false)
}

func (m *MapKeysPattern) ValidateAll() error {
	return m.validate(true)
}

func (m *MapKeysPattern) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	{
		if all {
			sorted_keys := make([]string, len(m.GetVal()))
			i := 0
			for key := range m.GetVal() {
				sorted_keys[i] = key
				i++
			}
			sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
			for _, key := range sorted_keys {
				val := m.GetVal()[key]
				_ = val

				if !_MapKeysPattern_Val_Pattern.MatchString(key) {
					err := mapsValidationError(
						0,
						fmt.Sprintf("[Val] value does not match regex pattern '%s'", "^[a-z0-9]+$"),
						nil,
					)
					if !all {
						return err
					}
					errors = append(errors, err)
				}
				// no validation rules for Val

			}
		} else {
			for key, val := range m.GetVal() {
				_, _ = key, val

				if !_MapKeysPattern_Val_Pattern.MatchString(key) {
					err := mapsValidationError(
						0,
						fmt.Sprintf("[Val] value does not match regex pattern '%s'", "^[a-z0-9]+$"),
						nil,
					)
					if !all {
						return err
					}
					errors = append(errors, err)
				}
				// no validation rules for Val

			}
		}
	}

	if len(errors) > 0 {
		return mapsMultiError(errors)
	}
	return nil
}

var _MapKeysPattern_Val_Pattern = regexp.MustCompile("^[a-z0-9]+$")

func (m *MapValuesPattern) Validate() error {
	return m.validate(false)
}

func (m *MapValuesPattern) ValidateAll() error {
	return m.validate(true)
}

func (m *MapValuesPattern) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	{
		if all {
			sorted_keys := make([]string, len(m.GetVal()))
			i := 0
			for key := range m.GetVal() {
				sorted_keys[i] = key
				i++
			}
			sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
			for _, key := range sorted_keys {
				val := m.GetVal()[key]
				_ = val

				// no validation rules for Val

				if !_MapValuesPattern_Val_Pattern.MatchString(val) {
					err := mapsValidationError(
						0,
						fmt.Sprintf("[Val] value does not match regex pattern '%s'", "(?i)^[a-z0-9]+$"),
						nil,
					)
					if !all {
						return err
					}
					errors = append(errors, err)
				}

			}
		} else {
			for key, val := range m.GetVal() {
				_, _ = key, val

				// no validation rules for Val

				if !_MapValuesPattern_Val_Pattern.MatchString(val) {
					err := mapsValidationError(
						0,
						fmt.Sprintf("[Val] value does not match regex pattern '%s'", "(?i)^[a-z0-9]+$"),
						nil,
					)
					if !all {
						return err
					}
					errors = append(errors, err)
				}

			}
		}
	}

	if len(errors) > 0 {
		return mapsMultiError(errors)
	}
	return nil
}

var _MapValuesPattern_Val_Pattern = regexp.MustCompile("(?i)^[a-z0-9]+$")

func (m *MapExactIgnore) Validate() error {
	return m.validate(false)
}

func (m *MapExactIgnore) ValidateAll() error {
	return m.validate(true)
}

func (m *MapExactIgnore) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if len(m.GetVal()) > 0 {
		if len(m.GetVal()) != 3 {
			err := mapsValidationError(
				0,
				"[Val] value must contain exactly 3 pair(s)",
				nil,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return mapsMultiError(errors)
	}
	return nil
}

func (m *MultipleMaps) Validate() error {
	return m.validate(false)
}

func (m *MultipleMaps) ValidateAll() error {
	return m.validate(true)
}

func (m *MultipleMaps) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	{
		if all {
			sorted_keys := make([]uint32, len(m.GetFirst()))
			i := 0
			for key := range m.GetFirst() {
				sorted_keys[i] = key
				i++
			}
			sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
			for _, key := range sorted_keys {
				val := m.GetFirst()[key]
				_ = val

				if key <= 0 {
					err := mapsValidationError(
						0,
						"[First] value must be greater than 0",
						nil,
					)
					if !all {
						return err
					}
					errors = append(errors, err)
				}

				// no validation rules for First

			}
		} else {
			for key, val := range m.GetFirst() {
				_, _ = key, val

				if key <= 0 {
					err := mapsValidationError(
						0,
						"[First] value must be greater than 0",
						nil,
					)
					if !all {
						return err
					}
					errors = append(errors, err)
				}

				// no validation rules for First

			}
		}
	}

	{
		if all {
			sorted_keys := make([]int32, len(m.GetSecond()))
			i := 0
			for key := range m.GetSecond() {
				sorted_keys[i] = key
				i++
			}
			sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
			for _, key := range sorted_keys {
				val := m.GetSecond()[key]
				_ = val

				if key >= 0 {
					err := mapsValidationError(
						0,
						"[Second] value must be less than 0",
						nil,
					)
					if !all {
						return err
					}
					errors = append(errors, err)
				}

				// no validation rules for Second

			}
		} else {
			for key, val := range m.GetSecond() {
				_, _ = key, val

				if key >= 0 {
					err := mapsValidationError(
						0,
						"[Second] value must be less than 0",
						nil,
					)
					if !all {
						return err
					}
					errors = append(errors, err)
				}

				// no validation rules for Second

			}
		}
	}

	{
		if all {
			sorted_keys := make([]int32, len(m.GetThird()))
			i := 0
			for key := range m.GetThird() {
				sorted_keys[i] = key
				i++
			}
			sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
			for _, key := range sorted_keys {
				val := m.GetThird()[key]
				_ = val

				if key <= 0 {
					err := mapsValidationError(
						0,
						"[Third] value must be greater than 0",
						nil,
					)
					if !all {
						return err
					}
					errors = append(errors, err)
				}

				// no validation rules for Third

			}
		} else {
			for key, val := range m.GetThird() {
				_, _ = key, val

				if key <= 0 {
					err := mapsValidationError(
						0,
						"[Third] value must be greater than 0",
						nil,
					)
					if !all {
						return err
					}
					errors = append(errors, err)
				}

				// no validation rules for Third

			}
		}
	}

	if len(errors) > 0 {
		return mapsMultiError(errors)
	}
	return nil
}

func (m *MapKeysIn) Validate() error {
	return m.validate(false)
}

func (m *MapKeysIn) ValidateAll() error {
	return m.validate(true)
}

func (m *MapKeysIn) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	{
		if all {
			sorted_keys := make([]string, len(m.GetVal()))
			i := 0
			for key := range m.GetVal() {
				sorted_keys[i] = key
				i++
			}
			sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
			for _, key := range sorted_keys {
				val := m.GetVal()[key]
				_ = val

				if _, ok := _MapKeysIn_Val_InLookup[key]; !ok {
					err := mapsValidationError(
						0,
						"[Val] value must be in [foo bar]",
						nil,
					)
					if !all {
						return err
					}
					errors = append(errors, err)
				}

				// no validation rules for Val

			}
		} else {
			for key, val := range m.GetVal() {
				_, _ = key, val

				if _, ok := _MapKeysIn_Val_InLookup[key]; !ok {
					err := mapsValidationError(
						0,
						"[Val] value must be in [foo bar]",
						nil,
					)
					if !all {
						return err
					}
					errors = append(errors, err)
				}

				// no validation rules for Val

			}
		}
	}

	if len(errors) > 0 {
		return mapsMultiError(errors)
	}
	return nil
}

var _MapKeysIn_Val_InLookup = map[string]struct{}{
	"foo": {},
	"bar": {},
}

func (m *MapKeysNotIn) Validate() error {
	return m.validate(false)
}

func (m *MapKeysNotIn) ValidateAll() error {
	return m.validate(true)
}

func (m *MapKeysNotIn) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	{
		if all {
			sorted_keys := make([]string, len(m.GetVal()))
			i := 0
			for key := range m.GetVal() {
				sorted_keys[i] = key
				i++
			}
			sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
			for _, key := range sorted_keys {
				val := m.GetVal()[key]
				_ = val

				if _, ok := _MapKeysNotIn_Val_NotInLookup[key]; ok {
					err := mapsValidationError(
						0,
						"[Val] value must not be in [foo bar]",
						nil,
					)
					if !all {
						return err
					}
					errors = append(errors, err)
				}

				// no validation rules for Val

			}
		} else {
			for key, val := range m.GetVal() {
				_, _ = key, val

				if _, ok := _MapKeysNotIn_Val_NotInLookup[key]; ok {
					err := mapsValidationError(
						0,
						"[Val] value must not be in [foo bar]",
						nil,
					)
					if !all {
						return err
					}
					errors = append(errors, err)
				}

				// no validation rules for Val

			}
		}
	}

	if len(errors) > 0 {
		return mapsMultiError(errors)
	}
	return nil
}

var _MapKeysNotIn_Val_NotInLookup = map[string]struct{}{
	"foo": {},
	"bar": {},
}
