// Code generated by protoc-gen-go-validate. DO NOT EDIT.
// - protoc-gen-go-validate 1.0.0
// - protoc             v6.30.2
// source: cases/repeated.proto

package cases

import (
	"errors"
	"fmt"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/ml444/gkit/errorx"
)

// ensure the imports are used
var (
	_ = errors.New("")
	_ = fmt.Print
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = sort.Sort
)

func repeatedValidationError(errCode int32, msg string, cause error) error {
	err := errorx.CreateError(400, errCode, msg)
	if cause != nil {
		err = err.WithCause(cause)
	}
	return err
}

// repeatedMultiError is an error wrapping multiple validation errors
// returned by .ValidateAll() if the designated constraints aren't met.
type repeatedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m repeatedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m repeatedMultiError) AllErrors() []error { return m }

func (m *Embed) Validate() error {
	return m.validate(false)
}

func (m *Embed) ValidateAll() error {
	return m.validate(true)
}

func (m *Embed) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if m.GetVal() <= 0 {
		err := repeatedValidationError(
			0,
			"[Val] value must be greater than 0",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return repeatedMultiError(errors)
	}
	return nil
}

func (m *RepeatedMin) Validate() error {
	return m.validate(false)
}

func (m *RepeatedMin) ValidateAll() error {
	return m.validate(true)
}

func (m *RepeatedMin) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	if len(m.GetVal()) < 2 {
		err := repeatedValidationError(
			0,
			"[Val] value must contain at least 2 item(s)",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return repeatedMultiError(errors)
	}
	return nil
}

func (m *RepeatedMax) Validate() error {
	return m.validate(false)
}

func (m *RepeatedMax) ValidateAll() error {
	return m.validate(true)
}

func (m *RepeatedMax) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	if len(m.GetVal()) > 3 {
		err := repeatedValidationError(
			0,
			"[Val] value must contain no more than 3 item(s)",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return repeatedMultiError(errors)
	}
	return nil
}

func (m *RepeatedMinMax) Validate() error {
	return m.validate(false)
}

func (m *RepeatedMinMax) ValidateAll() error {
	return m.validate(true)
}

func (m *RepeatedMinMax) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	if l := len(m.GetVal()); l < 2 || l > 4 {
		err := repeatedValidationError(
			0,
			"[Val] value must contain between 2 and 4 items, inclusive",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return repeatedMultiError(errors)
	}
	return nil
}

func (m *RepeatedExact) Validate() error {
	return m.validate(false)
}

func (m *RepeatedExact) ValidateAll() error {
	return m.validate(true)
}

func (m *RepeatedExact) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	if len(m.GetVal()) != 3 {
		err := repeatedValidationError(
			0,
			"[Val] value must contain exactly 3 item(s)",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return repeatedMultiError(errors)
	}
	return nil
}

func (m *RepeatedUnique) Validate() error {
	return m.validate(false)
}

func (m *RepeatedUnique) ValidateAll() error {
	return m.validate(true)
}

func (m *RepeatedUnique) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	_RepeatedUnique_Val_Unique := make(map[string]struct{}, len(m.GetVal()))
	for idx, item := range m.GetVal() {
		_, _ = idx, item
		if _, exists := _RepeatedUnique_Val_Unique[item]; exists {
			err := repeatedValidationError(
				0,
				fmt.Sprintf("[Val][%v] repeated value must contain unique items", idx),
				nil,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			_RepeatedUnique_Val_Unique[item] = struct{}{}
		}

	}

	if len(errors) > 0 {
		return repeatedMultiError(errors)
	}
	return nil
}

func (m *RepeatedItemRule) Validate() error {
	return m.validate(false)
}

func (m *RepeatedItemRule) ValidateAll() error {
	return m.validate(true)
}

func (m *RepeatedItemRule) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	for idx, item := range m.GetVal() {
		_, _ = idx, item

		if item <= 0 {
			err := repeatedValidationError(
				0,
				"[Val] value must be greater than 0",
				nil,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return repeatedMultiError(errors)
	}
	return nil
}

func (m *RepeatedItemPattern) Validate() error {
	return m.validate(false)
}

func (m *RepeatedItemPattern) ValidateAll() error {
	return m.validate(true)
}

func (m *RepeatedItemPattern) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	for idx, item := range m.GetVal() {
		_, _ = idx, item

		if !_RepeatedItemPattern_Val_Pattern.MatchString(item) {
			err := repeatedValidationError(
				0,
				fmt.Sprintf("[Val] value does not match regex pattern '%s'", "(?i)^[a-z0-9]+$"),
				nil,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return repeatedMultiError(errors)
	}
	return nil
}

var _RepeatedItemPattern_Val_Pattern = regexp.MustCompile("(?i)^[a-z0-9]+$")

func (m *RepeatedEmbedSkip) Validate() error {
	return m.validate(false)
}

func (m *RepeatedEmbedSkip) ValidateAll() error {
	return m.validate(true)
}

func (m *RepeatedEmbedSkip) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	for idx, item := range m.GetVal() {
		_, _ = idx, item

	}

	if len(errors) > 0 {
		return repeatedMultiError(errors)
	}
	return nil
}

func (m *RepeatedItemIn) Validate() error {
	return m.validate(false)
}

func (m *RepeatedItemIn) ValidateAll() error {
	return m.validate(true)
}

func (m *RepeatedItemIn) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	for idx, item := range m.GetVal() {
		_, _ = idx, item

		if _, ok := _RepeatedItemIn_Val_InLookup[item]; !ok {
			err := repeatedValidationError(
				0,
				"[Val] value must be in [foo bar]",
				nil,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return repeatedMultiError(errors)
	}
	return nil
}

var _RepeatedItemIn_Val_InLookup = map[string]struct{}{
	"foo": {},
	"bar": {},
}

func (m *RepeatedItemNotIn) Validate() error {
	return m.validate(false)
}

func (m *RepeatedItemNotIn) ValidateAll() error {
	return m.validate(true)
}

func (m *RepeatedItemNotIn) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	for idx, item := range m.GetVal() {
		_, _ = idx, item

		if _, ok := _RepeatedItemNotIn_Val_NotInLookup[item]; ok {
			err := repeatedValidationError(
				0,
				"[Val] value must not be in [foo bar]",
				nil,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return repeatedMultiError(errors)
	}
	return nil
}

var _RepeatedItemNotIn_Val_NotInLookup = map[string]struct{}{
	"foo": {},
	"bar": {},
}

func (m *RepeatedEnumIn) Validate() error {
	return m.validate(false)
}

func (m *RepeatedEnumIn) ValidateAll() error {
	return m.validate(true)
}

func (m *RepeatedEnumIn) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	for idx, item := range m.GetVal() {
		_, _ = idx, item

		if _, ok := _RepeatedEnumIn_Val_InLookup[item]; !ok {
			err := repeatedValidationError(
				0,
				"[Val] value must be in [X]",
				nil,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return repeatedMultiError(errors)
	}
	return nil
}

var _RepeatedEnumIn_Val_InLookup = map[AnEnum]struct{}{
	0: {},
}

func (m *RepeatedEnumNotIn) Validate() error {
	return m.validate(false)
}

func (m *RepeatedEnumNotIn) ValidateAll() error {
	return m.validate(true)
}

func (m *RepeatedEnumNotIn) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	for idx, item := range m.GetVal() {
		_, _ = idx, item

		if _, ok := _RepeatedEnumNotIn_Val_NotInLookup[item]; ok {
			err := repeatedValidationError(
				0,
				"[Val] value must not be in [X]",
				nil,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return repeatedMultiError(errors)
	}
	return nil
}

var _RepeatedEnumNotIn_Val_NotInLookup = map[AnEnum]struct{}{
	0: {},
}

func (m *RepeatedEmbeddedEnumIn) Validate() error {
	return m.validate(false)
}

func (m *RepeatedEmbeddedEnumIn) ValidateAll() error {
	return m.validate(true)
}

func (m *RepeatedEmbeddedEnumIn) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	for idx, item := range m.GetVal() {
		_, _ = idx, item

		if _, ok := _RepeatedEmbeddedEnumIn_Val_InLookup[item]; !ok {
			err := repeatedValidationError(
				0,
				"[Val] value must be in [A]",
				nil,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return repeatedMultiError(errors)
	}
	return nil
}

var _RepeatedEmbeddedEnumIn_Val_InLookup = map[RepeatedEmbeddedEnumIn_AnotherInEnum]struct{}{
	0: {},
}

func (m *RepeatedEmbeddedEnumNotIn) Validate() error {
	return m.validate(false)
}

func (m *RepeatedEmbeddedEnumNotIn) ValidateAll() error {
	return m.validate(true)
}

func (m *RepeatedEmbeddedEnumNotIn) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	for idx, item := range m.GetVal() {
		_, _ = idx, item

		if _, ok := _RepeatedEmbeddedEnumNotIn_Val_NotInLookup[item]; ok {
			err := repeatedValidationError(
				0,
				"[Val] value must not be in [A]",
				nil,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return repeatedMultiError(errors)
	}
	return nil
}

var _RepeatedEmbeddedEnumNotIn_Val_NotInLookup = map[RepeatedEmbeddedEnumNotIn_AnotherNotInEnum]struct{}{
	0: {},
}

func (m *RepeatedAnyIn) Validate() error {
	return m.validate(false)
}

func (m *RepeatedAnyIn) ValidateAll() error {
	return m.validate(true)
}

func (m *RepeatedAnyIn) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	for idx, item := range m.GetVal() {
		_, _ = idx, item

		if a := item; a != nil {
			if _, ok := _RepeatedAnyIn_Val_InLookup[a.GetTypeUrl()]; !ok {
				err := repeatedValidationError(
					0,
					"[Val] type URL must be in [type.googleapis.com/google.protobuf.Duration]",
					nil,
				)
				if !all {
					return err
				}
				errors = append(errors, err)
			}
		}

	}

	if len(errors) > 0 {
		return repeatedMultiError(errors)
	}
	return nil
}

var _RepeatedAnyIn_Val_InLookup = map[string]struct{}{
	"type.googleapis.com/google.protobuf.Duration": {},
}

func (m *RepeatedAnyNotIn) Validate() error {
	return m.validate(false)
}

func (m *RepeatedAnyNotIn) ValidateAll() error {
	return m.validate(true)
}

func (m *RepeatedAnyNotIn) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	for idx, item := range m.GetVal() {
		_, _ = idx, item

		if a := item; a != nil {
			if _, ok := _RepeatedAnyNotIn_Val_NotInLookup[a.GetTypeUrl()]; ok {
				err := repeatedValidationError(
					0,
					"[Val] type URL must not be in [type.googleapis.com/google.protobuf.Timestamp]",
					nil,
				)
				if !all {
					return err
				}
				errors = append(errors, err)
			}
		}

	}

	if len(errors) > 0 {
		return repeatedMultiError(errors)
	}
	return nil
}

var _RepeatedAnyNotIn_Val_NotInLookup = map[string]struct{}{
	"type.googleapis.com/google.protobuf.Timestamp": {},
}

func (m *RepeatedMinAndItemLen) Validate() error {
	return m.validate(false)
}

func (m *RepeatedMinAndItemLen) ValidateAll() error {
	return m.validate(true)
}

func (m *RepeatedMinAndItemLen) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	if len(m.GetVal()) < 1 {
		err := repeatedValidationError(
			0,
			"[Val] value must contain at least 1 item(s)",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}
	for idx, item := range m.GetVal() {
		_, _ = idx, item

		if utf8.RuneCountInString(item) != 3 {
			err := repeatedValidationError(
				0,
				"[Val] value length must be 3 runes",
				nil,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return repeatedMultiError(errors)
	}
	return nil
}

func (m *RepeatedMinAndMaxItemLen) Validate() error {
	return m.validate(false)
}

func (m *RepeatedMinAndMaxItemLen) ValidateAll() error {
	return m.validate(true)
}

func (m *RepeatedMinAndMaxItemLen) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	if l := len(m.GetVal()); l < 1 || l > 3 {
		err := repeatedValidationError(
			0,
			"[Val] value must contain between 1 and 3 items, inclusive",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return repeatedMultiError(errors)
	}
	return nil
}

func (m *RepeatedDuration) Validate() error {
	return m.validate(false)
}

func (m *RepeatedDuration) ValidateAll() error {
	return m.validate(true)
}

func (m *RepeatedDuration) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	for idx, item := range m.GetVal() {
		_, _ = idx, item

		if d := item; d != nil {
			dur, err := d.AsDuration(), d.CheckValid()
			if err != nil {
				err := repeatedValidationError(
					0,
					"[Val] value is not a valid duration",
					nil,
				)
				if !all {
					return err
				}
				errors = append(errors, err)
			} else {
				gte := time.Duration(0*time.Second + 1000000*time.Nanosecond)
				if dur < gte {
					err := repeatedValidationError(
						0,
						"[Val] value must be greater than or equal to 1ms",
						nil,
					)
					if !all {
						return err
					}
					errors = append(errors, err)
				}

			}
		}

	}

	if len(errors) > 0 {
		return repeatedMultiError(errors)
	}
	return nil
}

func (m *RepeatedExactIgnore) Validate() error {
	return m.validate(false)
}

func (m *RepeatedExactIgnore) ValidateAll() error {
	return m.validate(true)
}

func (m *RepeatedExactIgnore) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	if len(m.GetVal()) > 0 {
		if len(m.GetVal()) != 3 {
			err := repeatedValidationError(
				0,
				"[Val] value must contain exactly 3 item(s)",
				nil,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		}
	}

	if len(errors) > 0 {
		return repeatedMultiError(errors)
	}
	return nil
}
