// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: cases/strings.proto

package cases

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/ml444/gkit/cmd/protoc-gen-go-validate/v"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StringNone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringNone) Reset() {
	*x = StringNone{}
	mi := &file_cases_strings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringNone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringNone) ProtoMessage() {}

func (x *StringNone) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringNone.ProtoReflect.Descriptor instead.
func (*StringNone) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{0}
}

func (x *StringNone) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringConst struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringConst) Reset() {
	*x = StringConst{}
	mi := &file_cases_strings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringConst) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringConst) ProtoMessage() {}

func (x *StringConst) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringConst.ProtoReflect.Descriptor instead.
func (*StringConst) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{1}
}

func (x *StringConst) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringIn) Reset() {
	*x = StringIn{}
	mi := &file_cases_strings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringIn) ProtoMessage() {}

func (x *StringIn) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringIn.ProtoReflect.Descriptor instead.
func (*StringIn) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{2}
}

func (x *StringIn) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringNotIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringNotIn) Reset() {
	*x = StringNotIn{}
	mi := &file_cases_strings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringNotIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringNotIn) ProtoMessage() {}

func (x *StringNotIn) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringNotIn.ProtoReflect.Descriptor instead.
func (*StringNotIn) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{3}
}

func (x *StringNotIn) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringLen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringLen) Reset() {
	*x = StringLen{}
	mi := &file_cases_strings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringLen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringLen) ProtoMessage() {}

func (x *StringLen) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringLen.ProtoReflect.Descriptor instead.
func (*StringLen) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{4}
}

func (x *StringLen) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringMinLen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringMinLen) Reset() {
	*x = StringMinLen{}
	mi := &file_cases_strings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringMinLen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMinLen) ProtoMessage() {}

func (x *StringMinLen) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMinLen.ProtoReflect.Descriptor instead.
func (*StringMinLen) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{5}
}

func (x *StringMinLen) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringMaxLen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringMaxLen) Reset() {
	*x = StringMaxLen{}
	mi := &file_cases_strings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringMaxLen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMaxLen) ProtoMessage() {}

func (x *StringMaxLen) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMaxLen.ProtoReflect.Descriptor instead.
func (*StringMaxLen) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{6}
}

func (x *StringMaxLen) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringMinMaxLen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringMinMaxLen) Reset() {
	*x = StringMinMaxLen{}
	mi := &file_cases_strings_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringMinMaxLen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMinMaxLen) ProtoMessage() {}

func (x *StringMinMaxLen) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMinMaxLen.ProtoReflect.Descriptor instead.
func (*StringMinMaxLen) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{7}
}

func (x *StringMinMaxLen) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringEqualMinMaxLen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringEqualMinMaxLen) Reset() {
	*x = StringEqualMinMaxLen{}
	mi := &file_cases_strings_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringEqualMinMaxLen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringEqualMinMaxLen) ProtoMessage() {}

func (x *StringEqualMinMaxLen) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringEqualMinMaxLen.ProtoReflect.Descriptor instead.
func (*StringEqualMinMaxLen) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{8}
}

func (x *StringEqualMinMaxLen) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringLenBytes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringLenBytes) Reset() {
	*x = StringLenBytes{}
	mi := &file_cases_strings_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringLenBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringLenBytes) ProtoMessage() {}

func (x *StringLenBytes) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringLenBytes.ProtoReflect.Descriptor instead.
func (*StringLenBytes) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{9}
}

func (x *StringLenBytes) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringMinBytes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringMinBytes) Reset() {
	*x = StringMinBytes{}
	mi := &file_cases_strings_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringMinBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMinBytes) ProtoMessage() {}

func (x *StringMinBytes) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMinBytes.ProtoReflect.Descriptor instead.
func (*StringMinBytes) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{10}
}

func (x *StringMinBytes) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringMaxBytes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringMaxBytes) Reset() {
	*x = StringMaxBytes{}
	mi := &file_cases_strings_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringMaxBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMaxBytes) ProtoMessage() {}

func (x *StringMaxBytes) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMaxBytes.ProtoReflect.Descriptor instead.
func (*StringMaxBytes) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{11}
}

func (x *StringMaxBytes) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringMinMaxBytes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringMinMaxBytes) Reset() {
	*x = StringMinMaxBytes{}
	mi := &file_cases_strings_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringMinMaxBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMinMaxBytes) ProtoMessage() {}

func (x *StringMinMaxBytes) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMinMaxBytes.ProtoReflect.Descriptor instead.
func (*StringMinMaxBytes) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{12}
}

func (x *StringMinMaxBytes) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringEqualMinMaxBytes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringEqualMinMaxBytes) Reset() {
	*x = StringEqualMinMaxBytes{}
	mi := &file_cases_strings_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringEqualMinMaxBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringEqualMinMaxBytes) ProtoMessage() {}

func (x *StringEqualMinMaxBytes) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringEqualMinMaxBytes.ProtoReflect.Descriptor instead.
func (*StringEqualMinMaxBytes) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{13}
}

func (x *StringEqualMinMaxBytes) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringPattern struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringPattern) Reset() {
	*x = StringPattern{}
	mi := &file_cases_strings_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringPattern) ProtoMessage() {}

func (x *StringPattern) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringPattern.ProtoReflect.Descriptor instead.
func (*StringPattern) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{14}
}

func (x *StringPattern) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringPatternEscapes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringPatternEscapes) Reset() {
	*x = StringPatternEscapes{}
	mi := &file_cases_strings_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringPatternEscapes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringPatternEscapes) ProtoMessage() {}

func (x *StringPatternEscapes) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringPatternEscapes.ProtoReflect.Descriptor instead.
func (*StringPatternEscapes) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{15}
}

func (x *StringPatternEscapes) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringPrefix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringPrefix) Reset() {
	*x = StringPrefix{}
	mi := &file_cases_strings_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringPrefix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringPrefix) ProtoMessage() {}

func (x *StringPrefix) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringPrefix.ProtoReflect.Descriptor instead.
func (*StringPrefix) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{16}
}

func (x *StringPrefix) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringContains struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringContains) Reset() {
	*x = StringContains{}
	mi := &file_cases_strings_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringContains) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringContains) ProtoMessage() {}

func (x *StringContains) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringContains.ProtoReflect.Descriptor instead.
func (*StringContains) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{17}
}

func (x *StringContains) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringNotContains struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringNotContains) Reset() {
	*x = StringNotContains{}
	mi := &file_cases_strings_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringNotContains) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringNotContains) ProtoMessage() {}

func (x *StringNotContains) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringNotContains.ProtoReflect.Descriptor instead.
func (*StringNotContains) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{18}
}

func (x *StringNotContains) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringSuffix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringSuffix) Reset() {
	*x = StringSuffix{}
	mi := &file_cases_strings_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringSuffix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringSuffix) ProtoMessage() {}

func (x *StringSuffix) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringSuffix.ProtoReflect.Descriptor instead.
func (*StringSuffix) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{19}
}

func (x *StringSuffix) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringEmail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringEmail) Reset() {
	*x = StringEmail{}
	mi := &file_cases_strings_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringEmail) ProtoMessage() {}

func (x *StringEmail) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringEmail.ProtoReflect.Descriptor instead.
func (*StringEmail) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{20}
}

func (x *StringEmail) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringAddress) Reset() {
	*x = StringAddress{}
	mi := &file_cases_strings_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringAddress) ProtoMessage() {}

func (x *StringAddress) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringAddress.ProtoReflect.Descriptor instead.
func (*StringAddress) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{21}
}

func (x *StringAddress) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringHostname struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringHostname) Reset() {
	*x = StringHostname{}
	mi := &file_cases_strings_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringHostname) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringHostname) ProtoMessage() {}

func (x *StringHostname) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringHostname.ProtoReflect.Descriptor instead.
func (*StringHostname) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{22}
}

func (x *StringHostname) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringIP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringIP) Reset() {
	*x = StringIP{}
	mi := &file_cases_strings_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringIP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringIP) ProtoMessage() {}

func (x *StringIP) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringIP.ProtoReflect.Descriptor instead.
func (*StringIP) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{23}
}

func (x *StringIP) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringIPv4 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringIPv4) Reset() {
	*x = StringIPv4{}
	mi := &file_cases_strings_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringIPv4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringIPv4) ProtoMessage() {}

func (x *StringIPv4) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringIPv4.ProtoReflect.Descriptor instead.
func (*StringIPv4) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{24}
}

func (x *StringIPv4) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringIPv6 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringIPv6) Reset() {
	*x = StringIPv6{}
	mi := &file_cases_strings_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringIPv6) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringIPv6) ProtoMessage() {}

func (x *StringIPv6) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringIPv6.ProtoReflect.Descriptor instead.
func (*StringIPv6) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{25}
}

func (x *StringIPv6) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringURI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringURI) Reset() {
	*x = StringURI{}
	mi := &file_cases_strings_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringURI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringURI) ProtoMessage() {}

func (x *StringURI) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringURI.ProtoReflect.Descriptor instead.
func (*StringURI) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{26}
}

func (x *StringURI) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringURIRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringURIRef) Reset() {
	*x = StringURIRef{}
	mi := &file_cases_strings_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringURIRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringURIRef) ProtoMessage() {}

func (x *StringURIRef) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringURIRef.ProtoReflect.Descriptor instead.
func (*StringURIRef) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{27}
}

func (x *StringURIRef) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringUUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringUUID) Reset() {
	*x = StringUUID{}
	mi := &file_cases_strings_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringUUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringUUID) ProtoMessage() {}

func (x *StringUUID) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringUUID.ProtoReflect.Descriptor instead.
func (*StringUUID) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{28}
}

func (x *StringUUID) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringHttpHeaderName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringHttpHeaderName) Reset() {
	*x = StringHttpHeaderName{}
	mi := &file_cases_strings_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringHttpHeaderName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringHttpHeaderName) ProtoMessage() {}

func (x *StringHttpHeaderName) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringHttpHeaderName.ProtoReflect.Descriptor instead.
func (*StringHttpHeaderName) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{29}
}

func (x *StringHttpHeaderName) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringHttpHeaderValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringHttpHeaderValue) Reset() {
	*x = StringHttpHeaderValue{}
	mi := &file_cases_strings_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringHttpHeaderValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringHttpHeaderValue) ProtoMessage() {}

func (x *StringHttpHeaderValue) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringHttpHeaderValue.ProtoReflect.Descriptor instead.
func (*StringHttpHeaderValue) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{30}
}

func (x *StringHttpHeaderValue) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringValidHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringValidHeader) Reset() {
	*x = StringValidHeader{}
	mi := &file_cases_strings_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringValidHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringValidHeader) ProtoMessage() {}

func (x *StringValidHeader) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringValidHeader.ProtoReflect.Descriptor instead.
func (*StringValidHeader) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{31}
}

func (x *StringValidHeader) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringUUIDIgnore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringUUIDIgnore) Reset() {
	*x = StringUUIDIgnore{}
	mi := &file_cases_strings_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringUUIDIgnore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringUUIDIgnore) ProtoMessage() {}

func (x *StringUUIDIgnore) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringUUIDIgnore.ProtoReflect.Descriptor instead.
func (*StringUUIDIgnore) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{32}
}

func (x *StringUUIDIgnore) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type StringInOneOf struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Foo:
	//
	//	*StringInOneOf_Bar
	Foo           isStringInOneOf_Foo `protobuf_oneof:"foo"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringInOneOf) Reset() {
	*x = StringInOneOf{}
	mi := &file_cases_strings_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringInOneOf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringInOneOf) ProtoMessage() {}

func (x *StringInOneOf) ProtoReflect() protoreflect.Message {
	mi := &file_cases_strings_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringInOneOf.ProtoReflect.Descriptor instead.
func (*StringInOneOf) Descriptor() ([]byte, []int) {
	return file_cases_strings_proto_rawDescGZIP(), []int{33}
}

func (x *StringInOneOf) GetFoo() isStringInOneOf_Foo {
	if x != nil {
		return x.Foo
	}
	return nil
}

func (x *StringInOneOf) GetBar() string {
	if x != nil {
		if x, ok := x.Foo.(*StringInOneOf_Bar); ok {
			return x.Bar
		}
	}
	return ""
}

type isStringInOneOf_Foo interface {
	isStringInOneOf_Foo()
}

type StringInOneOf_Bar struct {
	Bar string `protobuf:"bytes,1,opt,name=bar,proto3,oneof"`
}

func (*StringInOneOf_Bar) isStringInOneOf_Foo() {}

var File_cases_strings_proto protoreflect.FileDescriptor

const file_cases_strings_proto_rawDesc = "" +
	"\n" +
	"\x13cases/strings.proto\x12\vtests.cases\x1a\tv/v.proto\"\x1e\n" +
	"\n" +
	"StringNone\x12\x10\n" +
	"\x03val\x18\x01 \x01(\tR\x03val\"+\n" +
	"\vStringConst\x12\x1c\n" +
	"\x03val\x18\x01 \x01(\tB\n" +
	"\xa2Z\ar\x05\n" +
	"\x03fooR\x03val\"-\n" +
	"\bStringIn\x12!\n" +
	"\x03val\x18\x01 \x01(\tB\x0f\xa2Z\fr\n" +
	"R\x03barR\x03bazR\x03val\"2\n" +
	"\vStringNotIn\x12#\n" +
	"\x03val\x18\x01 \x01(\tB\x11\xa2Z\x0er\fZ\x04fizzZ\x04buzzR\x03val\"'\n" +
	"\tStringLen\x12\x1a\n" +
	"\x03val\x18\x01 \x01(\tB\b\xa2Z\x05r\x03\x98\x01\x03R\x03val\")\n" +
	"\fStringMinLen\x12\x19\n" +
	"\x03val\x18\x01 \x01(\tB\a\xa2Z\x04r\x02\x10\x03R\x03val\")\n" +
	"\fStringMaxLen\x12\x19\n" +
	"\x03val\x18\x01 \x01(\tB\a\xa2Z\x04r\x02\x18\x05R\x03val\".\n" +
	"\x0fStringMinMaxLen\x12\x1b\n" +
	"\x03val\x18\x01 \x01(\tB\t\xa2Z\x06r\x04\x10\x03\x18\x05R\x03val\"3\n" +
	"\x14StringEqualMinMaxLen\x12\x1b\n" +
	"\x03val\x18\x01 \x01(\tB\t\xa2Z\x06r\x04\x10\x05\x18\x05R\x03val\",\n" +
	"\x0eStringLenBytes\x12\x1a\n" +
	"\x03val\x18\x01 \x01(\tB\b\xa2Z\x05r\x03\xa0\x01\x04R\x03val\"+\n" +
	"\x0eStringMinBytes\x12\x19\n" +
	"\x03val\x18\x01 \x01(\tB\a\xa2Z\x04r\x02 \x04R\x03val\"+\n" +
	"\x0eStringMaxBytes\x12\x19\n" +
	"\x03val\x18\x01 \x01(\tB\a\xa2Z\x04r\x02(\bR\x03val\"0\n" +
	"\x11StringMinMaxBytes\x12\x1b\n" +
	"\x03val\x18\x01 \x01(\tB\t\xa2Z\x06r\x04 \x04(\bR\x03val\"5\n" +
	"\x16StringEqualMinMaxBytes\x12\x1b\n" +
	"\x03val\x18\x01 \x01(\tB\t\xa2Z\x06r\x04 \x04(\bR\x03val\"9\n" +
	"\rStringPattern\x12(\n" +
	"\x03val\x18\x01 \x01(\tB\x16\xa2Z\x13r\x112\x0f(?i)^[a-z0-9]+$R\x03val\"9\n" +
	"\x14StringPatternEscapes\x12!\n" +
	"\x03val\x18\x01 \x01(\tB\x0f\xa2Z\fr\n" +
	"2\b\\* \\\\ \\wR\x03val\",\n" +
	"\fStringPrefix\x12\x1c\n" +
	"\x03val\x18\x01 \x01(\tB\n" +
	"\xa2Z\ar\x05:\x03fooR\x03val\".\n" +
	"\x0eStringContains\x12\x1c\n" +
	"\x03val\x18\x01 \x01(\tB\n" +
	"\xa2Z\ar\x05J\x03barR\x03val\"2\n" +
	"\x11StringNotContains\x12\x1d\n" +
	"\x03val\x18\x01 \x01(\tB\v\xa2Z\br\x06\xba\x01\x03barR\x03val\",\n" +
	"\fStringSuffix\x12\x1c\n" +
	"\x03val\x18\x01 \x01(\tB\n" +
	"\xa2Z\ar\x05B\x03bazR\x03val\"(\n" +
	"\vStringEmail\x12\x19\n" +
	"\x03val\x18\x01 \x01(\tB\a\xa2Z\x04r\x02`\x01R\x03val\"+\n" +
	"\rStringAddress\x12\x1a\n" +
	"\x03val\x18\x01 \x01(\tB\b\xa2Z\x05r\x03\xa8\x01\x01R\x03val\"+\n" +
	"\x0eStringHostname\x12\x19\n" +
	"\x03val\x18\x01 \x01(\tB\a\xa2Z\x04r\x02h\x01R\x03val\"%\n" +
	"\bStringIP\x12\x19\n" +
	"\x03val\x18\x01 \x01(\tB\a\xa2Z\x04r\x02p\x01R\x03val\"'\n" +
	"\n" +
	"StringIPv4\x12\x19\n" +
	"\x03val\x18\x01 \x01(\tB\a\xa2Z\x04r\x02x\x01R\x03val\"(\n" +
	"\n" +
	"StringIPv6\x12\x1a\n" +
	"\x03val\x18\x01 \x01(\tB\b\xa2Z\x05r\x03\x80\x01\x01R\x03val\"'\n" +
	"\tStringURI\x12\x1a\n" +
	"\x03val\x18\x01 \x01(\tB\b\xa2Z\x05r\x03\x88\x01\x01R\x03val\"*\n" +
	"\fStringURIRef\x12\x1a\n" +
	"\x03val\x18\x01 \x01(\tB\b\xa2Z\x05r\x03\x90\x01\x01R\x03val\"(\n" +
	"\n" +
	"StringUUID\x12\x1a\n" +
	"\x03val\x18\x01 \x01(\tB\b\xa2Z\x05r\x03\xb0\x01\x01R\x03val\"2\n" +
	"\x14StringHttpHeaderName\x12\x1a\n" +
	"\x03val\x18\x01 \x01(\tB\b\xa2Z\x05r\x03\xc0\x01\x01R\x03val\"3\n" +
	"\x15StringHttpHeaderValue\x12\x1a\n" +
	"\x03val\x18\x01 \x01(\tB\b\xa2Z\x05r\x03\xc0\x01\x02R\x03val\"2\n" +
	"\x11StringValidHeader\x12\x1d\n" +
	"\x03val\x18\x01 \x01(\tB\v\xa2Z\br\x06\xc8\x01\x00\xc0\x01\x02R\x03val\"1\n" +
	"\x10StringUUIDIgnore\x12\x1d\n" +
	"\x03val\x18\x01 \x01(\tB\v\xa2Z\br\x06\xd0\x01\x01\xb0\x01\x01R\x03val\"7\n" +
	"\rStringInOneOf\x12\x1f\n" +
	"\x03bar\x18\x01 \x01(\tB\v\xa2Z\br\x06R\x01aR\x01bH\x00R\x03barB\x05\n" +
	"\x03fooBGZEgithub.com/ml444/gkit/cmd/protoc-gen-go-validate/tests/cases/go;casesb\x06proto3"

var (
	file_cases_strings_proto_rawDescOnce sync.Once
	file_cases_strings_proto_rawDescData []byte
)

func file_cases_strings_proto_rawDescGZIP() []byte {
	file_cases_strings_proto_rawDescOnce.Do(func() {
		file_cases_strings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cases_strings_proto_rawDesc), len(file_cases_strings_proto_rawDesc)))
	})
	return file_cases_strings_proto_rawDescData
}

var file_cases_strings_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_cases_strings_proto_goTypes = []any{
	(*StringNone)(nil),             // 0: tests.cases.StringNone
	(*StringConst)(nil),            // 1: tests.cases.StringConst
	(*StringIn)(nil),               // 2: tests.cases.StringIn
	(*StringNotIn)(nil),            // 3: tests.cases.StringNotIn
	(*StringLen)(nil),              // 4: tests.cases.StringLen
	(*StringMinLen)(nil),           // 5: tests.cases.StringMinLen
	(*StringMaxLen)(nil),           // 6: tests.cases.StringMaxLen
	(*StringMinMaxLen)(nil),        // 7: tests.cases.StringMinMaxLen
	(*StringEqualMinMaxLen)(nil),   // 8: tests.cases.StringEqualMinMaxLen
	(*StringLenBytes)(nil),         // 9: tests.cases.StringLenBytes
	(*StringMinBytes)(nil),         // 10: tests.cases.StringMinBytes
	(*StringMaxBytes)(nil),         // 11: tests.cases.StringMaxBytes
	(*StringMinMaxBytes)(nil),      // 12: tests.cases.StringMinMaxBytes
	(*StringEqualMinMaxBytes)(nil), // 13: tests.cases.StringEqualMinMaxBytes
	(*StringPattern)(nil),          // 14: tests.cases.StringPattern
	(*StringPatternEscapes)(nil),   // 15: tests.cases.StringPatternEscapes
	(*StringPrefix)(nil),           // 16: tests.cases.StringPrefix
	(*StringContains)(nil),         // 17: tests.cases.StringContains
	(*StringNotContains)(nil),      // 18: tests.cases.StringNotContains
	(*StringSuffix)(nil),           // 19: tests.cases.StringSuffix
	(*StringEmail)(nil),            // 20: tests.cases.StringEmail
	(*StringAddress)(nil),          // 21: tests.cases.StringAddress
	(*StringHostname)(nil),         // 22: tests.cases.StringHostname
	(*StringIP)(nil),               // 23: tests.cases.StringIP
	(*StringIPv4)(nil),             // 24: tests.cases.StringIPv4
	(*StringIPv6)(nil),             // 25: tests.cases.StringIPv6
	(*StringURI)(nil),              // 26: tests.cases.StringURI
	(*StringURIRef)(nil),           // 27: tests.cases.StringURIRef
	(*StringUUID)(nil),             // 28: tests.cases.StringUUID
	(*StringHttpHeaderName)(nil),   // 29: tests.cases.StringHttpHeaderName
	(*StringHttpHeaderValue)(nil),  // 30: tests.cases.StringHttpHeaderValue
	(*StringValidHeader)(nil),      // 31: tests.cases.StringValidHeader
	(*StringUUIDIgnore)(nil),       // 32: tests.cases.StringUUIDIgnore
	(*StringInOneOf)(nil),          // 33: tests.cases.StringInOneOf
}
var file_cases_strings_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cases_strings_proto_init() }
func file_cases_strings_proto_init() {
	if File_cases_strings_proto != nil {
		return
	}
	file_cases_strings_proto_msgTypes[33].OneofWrappers = []any{
		(*StringInOneOf_Bar)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cases_strings_proto_rawDesc), len(file_cases_strings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cases_strings_proto_goTypes,
		DependencyIndexes: file_cases_strings_proto_depIdxs,
		MessageInfos:      file_cases_strings_proto_msgTypes,
	}.Build()
	File_cases_strings_proto = out.File
	file_cases_strings_proto_goTypes = nil
	file_cases_strings_proto_depIdxs = nil
}
