// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: cases/wkt_duration.proto

package cases

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/ml444/gkit/cmd/protoc-gen-go-validate/v"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DurationNone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *durationpb.Duration   `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurationNone) Reset() {
	*x = DurationNone{}
	mi := &file_cases_wkt_duration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurationNone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationNone) ProtoMessage() {}

func (x *DurationNone) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_duration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationNone.ProtoReflect.Descriptor instead.
func (*DurationNone) Descriptor() ([]byte, []int) {
	return file_cases_wkt_duration_proto_rawDescGZIP(), []int{0}
}

func (x *DurationNone) GetVal() *durationpb.Duration {
	if x != nil {
		return x.Val
	}
	return nil
}

type DurationRequired struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *durationpb.Duration   `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurationRequired) Reset() {
	*x = DurationRequired{}
	mi := &file_cases_wkt_duration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurationRequired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationRequired) ProtoMessage() {}

func (x *DurationRequired) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_duration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationRequired.ProtoReflect.Descriptor instead.
func (*DurationRequired) Descriptor() ([]byte, []int) {
	return file_cases_wkt_duration_proto_rawDescGZIP(), []int{1}
}

func (x *DurationRequired) GetVal() *durationpb.Duration {
	if x != nil {
		return x.Val
	}
	return nil
}

// TODO(htuch): Add a very large duration, e.g. {seconds: 315576000000}, once
// #34 is resolved.
type DurationConst struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *durationpb.Duration   `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurationConst) Reset() {
	*x = DurationConst{}
	mi := &file_cases_wkt_duration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurationConst) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationConst) ProtoMessage() {}

func (x *DurationConst) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_duration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationConst.ProtoReflect.Descriptor instead.
func (*DurationConst) Descriptor() ([]byte, []int) {
	return file_cases_wkt_duration_proto_rawDescGZIP(), []int{2}
}

func (x *DurationConst) GetVal() *durationpb.Duration {
	if x != nil {
		return x.Val
	}
	return nil
}

type DurationIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *durationpb.Duration   `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurationIn) Reset() {
	*x = DurationIn{}
	mi := &file_cases_wkt_duration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurationIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationIn) ProtoMessage() {}

func (x *DurationIn) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_duration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationIn.ProtoReflect.Descriptor instead.
func (*DurationIn) Descriptor() ([]byte, []int) {
	return file_cases_wkt_duration_proto_rawDescGZIP(), []int{3}
}

func (x *DurationIn) GetVal() *durationpb.Duration {
	if x != nil {
		return x.Val
	}
	return nil
}

type DurationNotIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *durationpb.Duration   `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurationNotIn) Reset() {
	*x = DurationNotIn{}
	mi := &file_cases_wkt_duration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurationNotIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationNotIn) ProtoMessage() {}

func (x *DurationNotIn) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_duration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationNotIn.ProtoReflect.Descriptor instead.
func (*DurationNotIn) Descriptor() ([]byte, []int) {
	return file_cases_wkt_duration_proto_rawDescGZIP(), []int{4}
}

func (x *DurationNotIn) GetVal() *durationpb.Duration {
	if x != nil {
		return x.Val
	}
	return nil
}

type DurationLT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *durationpb.Duration   `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurationLT) Reset() {
	*x = DurationLT{}
	mi := &file_cases_wkt_duration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurationLT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationLT) ProtoMessage() {}

func (x *DurationLT) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_duration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationLT.ProtoReflect.Descriptor instead.
func (*DurationLT) Descriptor() ([]byte, []int) {
	return file_cases_wkt_duration_proto_rawDescGZIP(), []int{5}
}

func (x *DurationLT) GetVal() *durationpb.Duration {
	if x != nil {
		return x.Val
	}
	return nil
}

type DurationLTE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *durationpb.Duration   `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurationLTE) Reset() {
	*x = DurationLTE{}
	mi := &file_cases_wkt_duration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurationLTE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationLTE) ProtoMessage() {}

func (x *DurationLTE) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_duration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationLTE.ProtoReflect.Descriptor instead.
func (*DurationLTE) Descriptor() ([]byte, []int) {
	return file_cases_wkt_duration_proto_rawDescGZIP(), []int{6}
}

func (x *DurationLTE) GetVal() *durationpb.Duration {
	if x != nil {
		return x.Val
	}
	return nil
}

type DurationGT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *durationpb.Duration   `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurationGT) Reset() {
	*x = DurationGT{}
	mi := &file_cases_wkt_duration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurationGT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationGT) ProtoMessage() {}

func (x *DurationGT) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_duration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationGT.ProtoReflect.Descriptor instead.
func (*DurationGT) Descriptor() ([]byte, []int) {
	return file_cases_wkt_duration_proto_rawDescGZIP(), []int{7}
}

func (x *DurationGT) GetVal() *durationpb.Duration {
	if x != nil {
		return x.Val
	}
	return nil
}

type DurationGTE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *durationpb.Duration   `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurationGTE) Reset() {
	*x = DurationGTE{}
	mi := &file_cases_wkt_duration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurationGTE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationGTE) ProtoMessage() {}

func (x *DurationGTE) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_duration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationGTE.ProtoReflect.Descriptor instead.
func (*DurationGTE) Descriptor() ([]byte, []int) {
	return file_cases_wkt_duration_proto_rawDescGZIP(), []int{8}
}

func (x *DurationGTE) GetVal() *durationpb.Duration {
	if x != nil {
		return x.Val
	}
	return nil
}

type DurationGTLT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *durationpb.Duration   `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurationGTLT) Reset() {
	*x = DurationGTLT{}
	mi := &file_cases_wkt_duration_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurationGTLT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationGTLT) ProtoMessage() {}

func (x *DurationGTLT) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_duration_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationGTLT.ProtoReflect.Descriptor instead.
func (*DurationGTLT) Descriptor() ([]byte, []int) {
	return file_cases_wkt_duration_proto_rawDescGZIP(), []int{9}
}

func (x *DurationGTLT) GetVal() *durationpb.Duration {
	if x != nil {
		return x.Val
	}
	return nil
}

type DurationExLTGT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *durationpb.Duration   `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurationExLTGT) Reset() {
	*x = DurationExLTGT{}
	mi := &file_cases_wkt_duration_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurationExLTGT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationExLTGT) ProtoMessage() {}

func (x *DurationExLTGT) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_duration_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationExLTGT.ProtoReflect.Descriptor instead.
func (*DurationExLTGT) Descriptor() ([]byte, []int) {
	return file_cases_wkt_duration_proto_rawDescGZIP(), []int{10}
}

func (x *DurationExLTGT) GetVal() *durationpb.Duration {
	if x != nil {
		return x.Val
	}
	return nil
}

type DurationGTELTE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *durationpb.Duration   `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurationGTELTE) Reset() {
	*x = DurationGTELTE{}
	mi := &file_cases_wkt_duration_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurationGTELTE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationGTELTE) ProtoMessage() {}

func (x *DurationGTELTE) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_duration_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationGTELTE.ProtoReflect.Descriptor instead.
func (*DurationGTELTE) Descriptor() ([]byte, []int) {
	return file_cases_wkt_duration_proto_rawDescGZIP(), []int{11}
}

func (x *DurationGTELTE) GetVal() *durationpb.Duration {
	if x != nil {
		return x.Val
	}
	return nil
}

type DurationExGTELTE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *durationpb.Duration   `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurationExGTELTE) Reset() {
	*x = DurationExGTELTE{}
	mi := &file_cases_wkt_duration_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurationExGTELTE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationExGTELTE) ProtoMessage() {}

func (x *DurationExGTELTE) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_duration_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationExGTELTE.ProtoReflect.Descriptor instead.
func (*DurationExGTELTE) Descriptor() ([]byte, []int) {
	return file_cases_wkt_duration_proto_rawDescGZIP(), []int{12}
}

func (x *DurationExGTELTE) GetVal() *durationpb.Duration {
	if x != nil {
		return x.Val
	}
	return nil
}

// Regression for earlier bug where missing Duration field would short circuit
// evaluation in C++.
type DurationFieldWithOtherFields struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DurationVal   *durationpb.Duration   `protobuf:"bytes,1,opt,name=duration_val,json=durationVal,proto3" json:"duration_val,omitempty"`
	IntVal        int32                  `protobuf:"varint,2,opt,name=int_val,json=intVal,proto3" json:"int_val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurationFieldWithOtherFields) Reset() {
	*x = DurationFieldWithOtherFields{}
	mi := &file_cases_wkt_duration_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurationFieldWithOtherFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationFieldWithOtherFields) ProtoMessage() {}

func (x *DurationFieldWithOtherFields) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_duration_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationFieldWithOtherFields.ProtoReflect.Descriptor instead.
func (*DurationFieldWithOtherFields) Descriptor() ([]byte, []int) {
	return file_cases_wkt_duration_proto_rawDescGZIP(), []int{13}
}

func (x *DurationFieldWithOtherFields) GetDurationVal() *durationpb.Duration {
	if x != nil {
		return x.DurationVal
	}
	return nil
}

func (x *DurationFieldWithOtherFields) GetIntVal() int32 {
	if x != nil {
		return x.IntVal
	}
	return 0
}

var File_cases_wkt_duration_proto protoreflect.FileDescriptor

const file_cases_wkt_duration_proto_rawDesc = "" +
	"\n" +
	"\x18cases/wkt_duration.proto\x12\vtests.cases\x1a\tv/v.proto\x1a\x1egoogle/protobuf/duration.proto\";\n" +
	"\fDurationNone\x12+\n" +
	"\x03val\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x03val\"I\n" +
	"\x10DurationRequired\x125\n" +
	"\x03val\x18\x01 \x01(\v2\x19.google.protobuf.DurationB\b\xa2Z\x05\xaa\x01\x02\b\x01R\x03val\"H\n" +
	"\rDurationConst\x127\n" +
	"\x03val\x18\x01 \x01(\v2\x19.google.protobuf.DurationB\n" +
	"\xa2Z\a\xaa\x01\x04\x12\x02\b\x03R\x03val\"J\n" +
	"\n" +
	"DurationIn\x12<\n" +
	"\x03val\x18\x01 \x01(\v2\x19.google.protobuf.DurationB\x0f\xa2Z\f\xaa\x01\t:\x02\b\x01:\x03\x10\xe8\aR\x03val\"F\n" +
	"\rDurationNotIn\x125\n" +
	"\x03val\x18\x01 \x01(\v2\x19.google.protobuf.DurationB\b\xa2Z\x05\xaa\x01\x02B\x00R\x03val\"C\n" +
	"\n" +
	"DurationLT\x125\n" +
	"\x03val\x18\x01 \x01(\v2\x19.google.protobuf.DurationB\b\xa2Z\x05\xaa\x01\x02\x1a\x00R\x03val\"F\n" +
	"\vDurationLTE\x127\n" +
	"\x03val\x18\x01 \x01(\v2\x19.google.protobuf.DurationB\n" +
	"\xa2Z\a\xaa\x01\x04\"\x02\b\x01R\x03val\"F\n" +
	"\n" +
	"DurationGT\x128\n" +
	"\x03val\x18\x01 \x01(\v2\x19.google.protobuf.DurationB\v\xa2Z\b\xaa\x01\x05*\x03\x10\xe8\aR\x03val\"H\n" +
	"\vDurationGTE\x129\n" +
	"\x03val\x18\x01 \x01(\v2\x19.google.protobuf.DurationB\f\xa2Z\t\xaa\x01\x062\x04\x10\xc0\x84=R\x03val\"I\n" +
	"\fDurationGTLT\x129\n" +
	"\x03val\x18\x01 \x01(\v2\x19.google.protobuf.DurationB\f\xa2Z\t\xaa\x01\x06\x1a\x02\b\x01*\x00R\x03val\"K\n" +
	"\x0eDurationExLTGT\x129\n" +
	"\x03val\x18\x01 \x01(\v2\x19.google.protobuf.DurationB\f\xa2Z\t\xaa\x01\x06\x1a\x00*\x02\b\x01R\x03val\"N\n" +
	"\x0eDurationGTELTE\x12<\n" +
	"\x03val\x18\x01 \x01(\v2\x19.google.protobuf.DurationB\x0f\xa2Z\f\xaa\x01\t\"\x03\b\x90\x1c2\x02\b<R\x03val\"P\n" +
	"\x10DurationExGTELTE\x12<\n" +
	"\x03val\x18\x01 \x01(\v2\x19.google.protobuf.DurationB\x0f\xa2Z\f\xaa\x01\t\"\x02\b<2\x03\b\x90\x1cR\x03val\"\x8a\x01\n" +
	"\x1cDurationFieldWithOtherFields\x12H\n" +
	"\fduration_val\x18\x01 \x01(\v2\x19.google.protobuf.DurationB\n" +
	"\xa2Z\a\xaa\x01\x04\"\x02\b\x01R\vdurationVal\x12 \n" +
	"\aint_val\x18\x02 \x01(\x05B\a\xa2Z\x04\x1a\x02 \x10R\x06intValBGZEgithub.com/ml444/gkit/cmd/protoc-gen-go-validate/tests/cases/go;casesb\x06proto3"

var (
	file_cases_wkt_duration_proto_rawDescOnce sync.Once
	file_cases_wkt_duration_proto_rawDescData []byte
)

func file_cases_wkt_duration_proto_rawDescGZIP() []byte {
	file_cases_wkt_duration_proto_rawDescOnce.Do(func() {
		file_cases_wkt_duration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cases_wkt_duration_proto_rawDesc), len(file_cases_wkt_duration_proto_rawDesc)))
	})
	return file_cases_wkt_duration_proto_rawDescData
}

var file_cases_wkt_duration_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_cases_wkt_duration_proto_goTypes = []any{
	(*DurationNone)(nil),                 // 0: tests.cases.DurationNone
	(*DurationRequired)(nil),             // 1: tests.cases.DurationRequired
	(*DurationConst)(nil),                // 2: tests.cases.DurationConst
	(*DurationIn)(nil),                   // 3: tests.cases.DurationIn
	(*DurationNotIn)(nil),                // 4: tests.cases.DurationNotIn
	(*DurationLT)(nil),                   // 5: tests.cases.DurationLT
	(*DurationLTE)(nil),                  // 6: tests.cases.DurationLTE
	(*DurationGT)(nil),                   // 7: tests.cases.DurationGT
	(*DurationGTE)(nil),                  // 8: tests.cases.DurationGTE
	(*DurationGTLT)(nil),                 // 9: tests.cases.DurationGTLT
	(*DurationExLTGT)(nil),               // 10: tests.cases.DurationExLTGT
	(*DurationGTELTE)(nil),               // 11: tests.cases.DurationGTELTE
	(*DurationExGTELTE)(nil),             // 12: tests.cases.DurationExGTELTE
	(*DurationFieldWithOtherFields)(nil), // 13: tests.cases.DurationFieldWithOtherFields
	(*durationpb.Duration)(nil),          // 14: google.protobuf.Duration
}
var file_cases_wkt_duration_proto_depIdxs = []int32{
	14, // 0: tests.cases.DurationNone.val:type_name -> google.protobuf.Duration
	14, // 1: tests.cases.DurationRequired.val:type_name -> google.protobuf.Duration
	14, // 2: tests.cases.DurationConst.val:type_name -> google.protobuf.Duration
	14, // 3: tests.cases.DurationIn.val:type_name -> google.protobuf.Duration
	14, // 4: tests.cases.DurationNotIn.val:type_name -> google.protobuf.Duration
	14, // 5: tests.cases.DurationLT.val:type_name -> google.protobuf.Duration
	14, // 6: tests.cases.DurationLTE.val:type_name -> google.protobuf.Duration
	14, // 7: tests.cases.DurationGT.val:type_name -> google.protobuf.Duration
	14, // 8: tests.cases.DurationGTE.val:type_name -> google.protobuf.Duration
	14, // 9: tests.cases.DurationGTLT.val:type_name -> google.protobuf.Duration
	14, // 10: tests.cases.DurationExLTGT.val:type_name -> google.protobuf.Duration
	14, // 11: tests.cases.DurationGTELTE.val:type_name -> google.protobuf.Duration
	14, // 12: tests.cases.DurationExGTELTE.val:type_name -> google.protobuf.Duration
	14, // 13: tests.cases.DurationFieldWithOtherFields.duration_val:type_name -> google.protobuf.Duration
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_cases_wkt_duration_proto_init() }
func file_cases_wkt_duration_proto_init() {
	if File_cases_wkt_duration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cases_wkt_duration_proto_rawDesc), len(file_cases_wkt_duration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cases_wkt_duration_proto_goTypes,
		DependencyIndexes: file_cases_wkt_duration_proto_depIdxs,
		MessageInfos:      file_cases_wkt_duration_proto_msgTypes,
	}.Build()
	File_cases_wkt_duration_proto = out.File
	file_cases_wkt_duration_proto_goTypes = nil
	file_cases_wkt_duration_proto_depIdxs = nil
}
