// Code generated by protoc-gen-go-validate. DO NOT EDIT.
// - protoc-gen-go-validate 1.0.0
// - protoc             v4.25.0--rc2
// source: cases/wkt_nested.proto

package cases

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"
	// "google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	//_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on WktLevelOne with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *WktLevelOne) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WktLevelOne with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in WktLevelOneMultiError, or
// nil if none found.
func (m *WktLevelOne) ValidateAll() error {
	return m.validate(true)
}

func (m *WktLevelOne) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetTwo() == nil {
		err := ValidationError{
			field:   "Two",
			reason:  "value is required",
			errCode: 0,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTwo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ValidationError{
					field:   "Two",
					reason:  "embedded message failed validation",
					errCode: 0,
					cause:   err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ValidationError{
					field:   "Two",
					reason:  "embedded message failed validation",
					errCode: 0,
					cause:   err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTwo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ValidationError{
				field:   "Two",
				reason:  "embedded message failed validation",
				errCode: 0,
				cause:   err,
			}
		}
	}

	if len(errors) > 0 {
		return MultiError(errors)
	}

	return nil
}
