// Code generated by protoc-gen-go-validate. DO NOT EDIT.
// - protoc-gen-go-validate 1.0.0
// - protoc             v6.30.2
// source: cases/wkt_timestamp.proto

package cases

import (
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/ml444/gkit/errorx"
)

// ensure the imports are used
var (
	_ = errors.New("")
	_ = fmt.Print
	_ = (*strings.Reader)(nil)
	_ = time.Duration(0)
)

func wkt_timestampValidationError(errCode int32, msg string, cause error) error {
	err := errorx.CreateError(400, errCode, msg)
	if cause != nil {
		err = err.WithCause(cause)
	}
	return err
}

// wkt_timestampMultiError is an error wrapping multiple validation errors
// returned by .ValidateAll() if the designated constraints aren't met.
type wkt_timestampMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m wkt_timestampMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m wkt_timestampMultiError) AllErrors() []error { return m }

func (m *TimestampRequired) Validate() error {
	return m.validate(false)
}

func (m *TimestampRequired) ValidateAll() error {
	return m.validate(true)
}

func (m *TimestampRequired) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	if m.GetVal() == nil {
		err := wkt_timestampValidationError(
			0,
			"[Val] value is required",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return wkt_timestampMultiError(errors)
	}
	return nil
}

func (m *TimestampConst) Validate() error {
	return m.validate(false)
}

func (m *TimestampConst) ValidateAll() error {
	return m.validate(true)
}

func (m *TimestampConst) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if t := m.GetVal(); t != nil {
		ts, e := t.AsTime(), t.CheckValid()
		if e != nil {
			err := wkt_timestampValidationError(
				0,
				"[Val] value is not a valid timestamp",
				e,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			if !ts.Equal(time.Unix(3, 0)) {
				err := wkt_timestampValidationError(
					0,
					"[Val] value must equal 1970-01-01 00:00:03 +0000 UTC",
					nil,
				)
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}
	}

	if len(errors) > 0 {
		return wkt_timestampMultiError(errors)
	}
	return nil
}

func (m *TimestampLT) Validate() error {
	return m.validate(false)
}

func (m *TimestampLT) ValidateAll() error {
	return m.validate(true)
}

func (m *TimestampLT) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if t := m.GetVal(); t != nil {
		ts, e := t.AsTime(), t.CheckValid()
		if e != nil {
			err := wkt_timestampValidationError(
				0,
				"[Val] value is not a valid timestamp",
				e,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			lt := time.Unix(0, 0)
			if ts.Sub(lt) >= 0 {
				err := wkt_timestampValidationError(
					0,
					"[Val] value must be less than 1970-01-01 00:00:00 +0000 UTC",
					nil,
				)
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}
	}

	if len(errors) > 0 {
		return wkt_timestampMultiError(errors)
	}
	return nil
}

func (m *TimestampLTE) Validate() error {
	return m.validate(false)
}

func (m *TimestampLTE) ValidateAll() error {
	return m.validate(true)
}

func (m *TimestampLTE) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if t := m.GetVal(); t != nil {
		ts, e := t.AsTime(), t.CheckValid()
		if e != nil {
			err := wkt_timestampValidationError(
				0,
				"[Val] value is not a valid timestamp",
				e,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			lte := time.Unix(1, 0)
			if ts.Sub(lte) > 0 {
				err := wkt_timestampValidationError(
					0,
					"[Val] value must be less than or equal to 1970-01-01 00:00:01 +0000 UTC",
					nil,
				)
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}
	}

	if len(errors) > 0 {
		return wkt_timestampMultiError(errors)
	}
	return nil
}

func (m *TimestampGT) Validate() error {
	return m.validate(false)
}

func (m *TimestampGT) ValidateAll() error {
	return m.validate(true)
}

func (m *TimestampGT) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if t := m.GetVal(); t != nil {
		ts, e := t.AsTime(), t.CheckValid()
		if e != nil {
			err := wkt_timestampValidationError(
				0,
				"[Val] value is not a valid timestamp",
				e,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			gt := time.Unix(0, 1000)
			if ts.Sub(gt) <= 0 {
				err := wkt_timestampValidationError(
					0,
					"[Val] value must be greater than 1970-01-01 00:00:00.000001 +0000 UTC",
					nil,
				)
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}
	}

	if len(errors) > 0 {
		return wkt_timestampMultiError(errors)
	}
	return nil
}

func (m *TimestampGTE) Validate() error {
	return m.validate(false)
}

func (m *TimestampGTE) ValidateAll() error {
	return m.validate(true)
}

func (m *TimestampGTE) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if t := m.GetVal(); t != nil {
		ts, e := t.AsTime(), t.CheckValid()
		if e != nil {
			err := wkt_timestampValidationError(
				0,
				"[Val] value is not a valid timestamp",
				e,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			gte := time.Unix(0, 1000000)
			if ts.Sub(gte) < 0 {
				err := wkt_timestampValidationError(
					0,
					"[Val] value must be greater than or equal to 1970-01-01 00:00:00.001 +0000 UTC",
					nil,
				)
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}
	}

	if len(errors) > 0 {
		return wkt_timestampMultiError(errors)
	}
	return nil
}

func (m *TimestampGTLT) Validate() error {
	return m.validate(false)
}

func (m *TimestampGTLT) ValidateAll() error {
	return m.validate(true)
}

func (m *TimestampGTLT) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if t := m.GetVal(); t != nil {
		ts, e := t.AsTime(), t.CheckValid()
		if e != nil {
			err := wkt_timestampValidationError(
				0,
				"[Val] value is not a valid timestamp",
				e,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			lt := time.Unix(1, 0)
			gt := time.Unix(0, 0)
			if ts.Sub(gt) <= 0 || ts.Sub(lt) >= 0 {
				err := wkt_timestampValidationError(
					0,
					"[Val] value must be inside range (1970-01-01 00:00:00 +0000 UTC, 1970-01-01 00:00:01 +0000 UTC)",
					nil,
				)
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}
	}

	if len(errors) > 0 {
		return wkt_timestampMultiError(errors)
	}
	return nil
}

func (m *TimestampExLTGT) Validate() error {
	return m.validate(false)
}

func (m *TimestampExLTGT) ValidateAll() error {
	return m.validate(true)
}

func (m *TimestampExLTGT) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if t := m.GetVal(); t != nil {
		ts, e := t.AsTime(), t.CheckValid()
		if e != nil {
			err := wkt_timestampValidationError(
				0,
				"[Val] value is not a valid timestamp",
				e,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			lt := time.Unix(0, 0)
			gt := time.Unix(1, 0)
			if ts.Sub(lt) >= 0 && ts.Sub(gt) <= 0 {
				err := wkt_timestampValidationError(
					0,
					"[Val] value must be outside range [1970-01-01 00:00:00 +0000 UTC, 1970-01-01 00:00:01 +0000 UTC]",
					nil,
				)
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}
	}

	if len(errors) > 0 {
		return wkt_timestampMultiError(errors)
	}
	return nil
}

func (m *TimestampGTELTE) Validate() error {
	return m.validate(false)
}

func (m *TimestampGTELTE) ValidateAll() error {
	return m.validate(true)
}

func (m *TimestampGTELTE) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if t := m.GetVal(); t != nil {
		ts, e := t.AsTime(), t.CheckValid()
		if e != nil {
			err := wkt_timestampValidationError(
				0,
				"[Val] value is not a valid timestamp",
				e,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			lte := time.Unix(3600, 0)
			gte := time.Unix(60, 0)
			if ts.Sub(gte) < 0 || ts.Sub(lte) > 0 {
				err := wkt_timestampValidationError(
					0,
					"[Val] value must be inside range [1970-01-01 00:01:00 +0000 UTC, 1970-01-01 01:00:00 +0000 UTC]",
					nil,
				)
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}
	}

	if len(errors) > 0 {
		return wkt_timestampMultiError(errors)
	}
	return nil
}

func (m *TimestampExGTELTE) Validate() error {
	return m.validate(false)
}

func (m *TimestampExGTELTE) ValidateAll() error {
	return m.validate(true)
}

func (m *TimestampExGTELTE) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if t := m.GetVal(); t != nil {
		ts, e := t.AsTime(), t.CheckValid()
		if e != nil {
			err := wkt_timestampValidationError(
				0,
				"[Val] value is not a valid timestamp",
				e,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			lte := time.Unix(60, 0)
			gte := time.Unix(3600, 0)
			if ts.Sub(lte) > 0 && ts.Sub(gte) < 0 {
				err := wkt_timestampValidationError(
					0,
					"[Val] value must be outside range (1970-01-01 00:01:00 +0000 UTC, 1970-01-01 01:00:00 +0000 UTC)",
					nil,
				)
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}
	}

	if len(errors) > 0 {
		return wkt_timestampMultiError(errors)
	}
	return nil
}

func (m *TimestampLTNow) Validate() error {
	return m.validate(false)
}

func (m *TimestampLTNow) ValidateAll() error {
	return m.validate(true)
}

func (m *TimestampLTNow) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if t := m.GetVal(); t != nil {
		ts, e := t.AsTime(), t.CheckValid()
		if e != nil {
			err := wkt_timestampValidationError(
				0,
				"[Val] value is not a valid timestamp",
				e,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			now := time.Now()
			if ts.Sub(now) >= 0 {
				err := wkt_timestampValidationError(
					0,
					"[Val] value must be less than now",
					nil,
				)
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}
	}

	if len(errors) > 0 {
		return wkt_timestampMultiError(errors)
	}
	return nil
}

func (m *TimestampGTNow) Validate() error {
	return m.validate(false)
}

func (m *TimestampGTNow) ValidateAll() error {
	return m.validate(true)
}

func (m *TimestampGTNow) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if t := m.GetVal(); t != nil {
		ts, e := t.AsTime(), t.CheckValid()
		if e != nil {
			err := wkt_timestampValidationError(
				0,
				"[Val] value is not a valid timestamp",
				e,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			now := time.Now()
			if ts.Sub(now) <= 0 {
				err := wkt_timestampValidationError(
					0,
					"[Val] value must be greater than now",
					nil,
				)
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}
	}

	if len(errors) > 0 {
		return wkt_timestampMultiError(errors)
	}
	return nil
}

func (m *TimestampWithin) Validate() error {
	return m.validate(false)
}

func (m *TimestampWithin) ValidateAll() error {
	return m.validate(true)
}

func (m *TimestampWithin) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if t := m.GetVal(); t != nil {
		ts, e := t.AsTime(), t.CheckValid()
		if e != nil {
			err := wkt_timestampValidationError(
				0,
				"[Val] value is not a valid timestamp",
				e,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			now := time.Now()
			within := time.Duration(3600*time.Second + 0*time.Nanosecond)
			if ts.Sub(now.Add(within)) >= 0 || ts.Sub(now.Add(-within)) <= 0 {
				err := wkt_timestampValidationError(
					0,
					"[Val] value must be within 1h0m0s of now",
					nil,
				)
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}
	}

	if len(errors) > 0 {
		return wkt_timestampMultiError(errors)
	}
	return nil
}

func (m *TimestampLTNowWithin) Validate() error {
	return m.validate(false)
}

func (m *TimestampLTNowWithin) ValidateAll() error {
	return m.validate(true)
}

func (m *TimestampLTNowWithin) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if t := m.GetVal(); t != nil {
		ts, e := t.AsTime(), t.CheckValid()
		if e != nil {
			err := wkt_timestampValidationError(
				0,
				"[Val] value is not a valid timestamp",
				e,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			now := time.Now()
			within := time.Duration(3600*time.Second + 0*time.Nanosecond)
			if ts.Sub(now) >= 0 || ts.Sub(now.Add(-within)) < 0 {
				err := wkt_timestampValidationError(
					0,
					"[Val] value must be less than now within 1h0m0s",
					nil,
				)
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}
	}

	if len(errors) > 0 {
		return wkt_timestampMultiError(errors)
	}
	return nil
}

func (m *TimestampGTNowWithin) Validate() error {
	return m.validate(false)
}

func (m *TimestampGTNowWithin) ValidateAll() error {
	return m.validate(true)
}

func (m *TimestampGTNowWithin) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if t := m.GetVal(); t != nil {
		ts, e := t.AsTime(), t.CheckValid()
		if e != nil {
			err := wkt_timestampValidationError(
				0,
				"[Val] value is not a valid timestamp",
				e,
			)
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			now := time.Now()
			within := time.Duration(3600*time.Second + 0*time.Nanosecond)
			if ts.Sub(now) <= 0 || ts.Sub(now.Add(within)) > 0 {
				err := wkt_timestampValidationError(
					0,
					"[Val] value must be greater than now within 1h0m0s",
					nil,
				)
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}
	}

	if len(errors) > 0 {
		return wkt_timestampMultiError(errors)
	}
	return nil
}
