// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: cases/wkt_timestamp.proto

package cases

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/ml444/gkit/cmd/protoc-gen-go-validate/v"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimestampNone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampNone) Reset() {
	*x = TimestampNone{}
	mi := &file_cases_wkt_timestamp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampNone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampNone) ProtoMessage() {}

func (x *TimestampNone) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_timestamp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampNone.ProtoReflect.Descriptor instead.
func (*TimestampNone) Descriptor() ([]byte, []int) {
	return file_cases_wkt_timestamp_proto_rawDescGZIP(), []int{0}
}

func (x *TimestampNone) GetVal() *timestamppb.Timestamp {
	if x != nil {
		return x.Val
	}
	return nil
}

type TimestampRequired struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampRequired) Reset() {
	*x = TimestampRequired{}
	mi := &file_cases_wkt_timestamp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampRequired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampRequired) ProtoMessage() {}

func (x *TimestampRequired) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_timestamp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampRequired.ProtoReflect.Descriptor instead.
func (*TimestampRequired) Descriptor() ([]byte, []int) {
	return file_cases_wkt_timestamp_proto_rawDescGZIP(), []int{1}
}

func (x *TimestampRequired) GetVal() *timestamppb.Timestamp {
	if x != nil {
		return x.Val
	}
	return nil
}

type TimestampConst struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampConst) Reset() {
	*x = TimestampConst{}
	mi := &file_cases_wkt_timestamp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampConst) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampConst) ProtoMessage() {}

func (x *TimestampConst) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_timestamp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampConst.ProtoReflect.Descriptor instead.
func (*TimestampConst) Descriptor() ([]byte, []int) {
	return file_cases_wkt_timestamp_proto_rawDescGZIP(), []int{2}
}

func (x *TimestampConst) GetVal() *timestamppb.Timestamp {
	if x != nil {
		return x.Val
	}
	return nil
}

type TimestampLT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampLT) Reset() {
	*x = TimestampLT{}
	mi := &file_cases_wkt_timestamp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampLT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampLT) ProtoMessage() {}

func (x *TimestampLT) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_timestamp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampLT.ProtoReflect.Descriptor instead.
func (*TimestampLT) Descriptor() ([]byte, []int) {
	return file_cases_wkt_timestamp_proto_rawDescGZIP(), []int{3}
}

func (x *TimestampLT) GetVal() *timestamppb.Timestamp {
	if x != nil {
		return x.Val
	}
	return nil
}

type TimestampLTE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampLTE) Reset() {
	*x = TimestampLTE{}
	mi := &file_cases_wkt_timestamp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampLTE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampLTE) ProtoMessage() {}

func (x *TimestampLTE) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_timestamp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampLTE.ProtoReflect.Descriptor instead.
func (*TimestampLTE) Descriptor() ([]byte, []int) {
	return file_cases_wkt_timestamp_proto_rawDescGZIP(), []int{4}
}

func (x *TimestampLTE) GetVal() *timestamppb.Timestamp {
	if x != nil {
		return x.Val
	}
	return nil
}

type TimestampGT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampGT) Reset() {
	*x = TimestampGT{}
	mi := &file_cases_wkt_timestamp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampGT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampGT) ProtoMessage() {}

func (x *TimestampGT) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_timestamp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampGT.ProtoReflect.Descriptor instead.
func (*TimestampGT) Descriptor() ([]byte, []int) {
	return file_cases_wkt_timestamp_proto_rawDescGZIP(), []int{5}
}

func (x *TimestampGT) GetVal() *timestamppb.Timestamp {
	if x != nil {
		return x.Val
	}
	return nil
}

type TimestampGTE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampGTE) Reset() {
	*x = TimestampGTE{}
	mi := &file_cases_wkt_timestamp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampGTE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampGTE) ProtoMessage() {}

func (x *TimestampGTE) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_timestamp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampGTE.ProtoReflect.Descriptor instead.
func (*TimestampGTE) Descriptor() ([]byte, []int) {
	return file_cases_wkt_timestamp_proto_rawDescGZIP(), []int{6}
}

func (x *TimestampGTE) GetVal() *timestamppb.Timestamp {
	if x != nil {
		return x.Val
	}
	return nil
}

type TimestampGTLT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampGTLT) Reset() {
	*x = TimestampGTLT{}
	mi := &file_cases_wkt_timestamp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampGTLT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampGTLT) ProtoMessage() {}

func (x *TimestampGTLT) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_timestamp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampGTLT.ProtoReflect.Descriptor instead.
func (*TimestampGTLT) Descriptor() ([]byte, []int) {
	return file_cases_wkt_timestamp_proto_rawDescGZIP(), []int{7}
}

func (x *TimestampGTLT) GetVal() *timestamppb.Timestamp {
	if x != nil {
		return x.Val
	}
	return nil
}

type TimestampExLTGT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampExLTGT) Reset() {
	*x = TimestampExLTGT{}
	mi := &file_cases_wkt_timestamp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampExLTGT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampExLTGT) ProtoMessage() {}

func (x *TimestampExLTGT) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_timestamp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampExLTGT.ProtoReflect.Descriptor instead.
func (*TimestampExLTGT) Descriptor() ([]byte, []int) {
	return file_cases_wkt_timestamp_proto_rawDescGZIP(), []int{8}
}

func (x *TimestampExLTGT) GetVal() *timestamppb.Timestamp {
	if x != nil {
		return x.Val
	}
	return nil
}

type TimestampGTELTE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampGTELTE) Reset() {
	*x = TimestampGTELTE{}
	mi := &file_cases_wkt_timestamp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampGTELTE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampGTELTE) ProtoMessage() {}

func (x *TimestampGTELTE) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_timestamp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampGTELTE.ProtoReflect.Descriptor instead.
func (*TimestampGTELTE) Descriptor() ([]byte, []int) {
	return file_cases_wkt_timestamp_proto_rawDescGZIP(), []int{9}
}

func (x *TimestampGTELTE) GetVal() *timestamppb.Timestamp {
	if x != nil {
		return x.Val
	}
	return nil
}

type TimestampExGTELTE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampExGTELTE) Reset() {
	*x = TimestampExGTELTE{}
	mi := &file_cases_wkt_timestamp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampExGTELTE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampExGTELTE) ProtoMessage() {}

func (x *TimestampExGTELTE) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_timestamp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampExGTELTE.ProtoReflect.Descriptor instead.
func (*TimestampExGTELTE) Descriptor() ([]byte, []int) {
	return file_cases_wkt_timestamp_proto_rawDescGZIP(), []int{10}
}

func (x *TimestampExGTELTE) GetVal() *timestamppb.Timestamp {
	if x != nil {
		return x.Val
	}
	return nil
}

type TimestampLTNow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampLTNow) Reset() {
	*x = TimestampLTNow{}
	mi := &file_cases_wkt_timestamp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampLTNow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampLTNow) ProtoMessage() {}

func (x *TimestampLTNow) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_timestamp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampLTNow.ProtoReflect.Descriptor instead.
func (*TimestampLTNow) Descriptor() ([]byte, []int) {
	return file_cases_wkt_timestamp_proto_rawDescGZIP(), []int{11}
}

func (x *TimestampLTNow) GetVal() *timestamppb.Timestamp {
	if x != nil {
		return x.Val
	}
	return nil
}

type TimestampGTNow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampGTNow) Reset() {
	*x = TimestampGTNow{}
	mi := &file_cases_wkt_timestamp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampGTNow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampGTNow) ProtoMessage() {}

func (x *TimestampGTNow) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_timestamp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampGTNow.ProtoReflect.Descriptor instead.
func (*TimestampGTNow) Descriptor() ([]byte, []int) {
	return file_cases_wkt_timestamp_proto_rawDescGZIP(), []int{12}
}

func (x *TimestampGTNow) GetVal() *timestamppb.Timestamp {
	if x != nil {
		return x.Val
	}
	return nil
}

type TimestampWithin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampWithin) Reset() {
	*x = TimestampWithin{}
	mi := &file_cases_wkt_timestamp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampWithin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampWithin) ProtoMessage() {}

func (x *TimestampWithin) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_timestamp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampWithin.ProtoReflect.Descriptor instead.
func (*TimestampWithin) Descriptor() ([]byte, []int) {
	return file_cases_wkt_timestamp_proto_rawDescGZIP(), []int{13}
}

func (x *TimestampWithin) GetVal() *timestamppb.Timestamp {
	if x != nil {
		return x.Val
	}
	return nil
}

type TimestampLTNowWithin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampLTNowWithin) Reset() {
	*x = TimestampLTNowWithin{}
	mi := &file_cases_wkt_timestamp_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampLTNowWithin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampLTNowWithin) ProtoMessage() {}

func (x *TimestampLTNowWithin) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_timestamp_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampLTNowWithin.ProtoReflect.Descriptor instead.
func (*TimestampLTNowWithin) Descriptor() ([]byte, []int) {
	return file_cases_wkt_timestamp_proto_rawDescGZIP(), []int{14}
}

func (x *TimestampLTNowWithin) GetVal() *timestamppb.Timestamp {
	if x != nil {
		return x.Val
	}
	return nil
}

type TimestampGTNowWithin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampGTNowWithin) Reset() {
	*x = TimestampGTNowWithin{}
	mi := &file_cases_wkt_timestamp_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampGTNowWithin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampGTNowWithin) ProtoMessage() {}

func (x *TimestampGTNowWithin) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_timestamp_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampGTNowWithin.ProtoReflect.Descriptor instead.
func (*TimestampGTNowWithin) Descriptor() ([]byte, []int) {
	return file_cases_wkt_timestamp_proto_rawDescGZIP(), []int{15}
}

func (x *TimestampGTNowWithin) GetVal() *timestamppb.Timestamp {
	if x != nil {
		return x.Val
	}
	return nil
}

var File_cases_wkt_timestamp_proto protoreflect.FileDescriptor

const file_cases_wkt_timestamp_proto_rawDesc = "" +
	"\n" +
	"\x19cases/wkt_timestamp.proto\x12\vtests.cases\x1a\tv/v.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"=\n" +
	"\rTimestampNone\x12,\n" +
	"\x03val\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x03val\"K\n" +
	"\x11TimestampRequired\x126\n" +
	"\x03val\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\b\xa2Z\x05\xb2\x01\x02\b\x01R\x03val\"J\n" +
	"\x0eTimestampConst\x128\n" +
	"\x03val\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\n" +
	"\xa2Z\a\xb2\x01\x04\x12\x02\b\x03R\x03val\"E\n" +
	"\vTimestampLT\x126\n" +
	"\x03val\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\b\xa2Z\x05\xb2\x01\x02\x1a\x00R\x03val\"H\n" +
	"\fTimestampLTE\x128\n" +
	"\x03val\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\n" +
	"\xa2Z\a\xb2\x01\x04\"\x02\b\x01R\x03val\"H\n" +
	"\vTimestampGT\x129\n" +
	"\x03val\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\v\xa2Z\b\xb2\x01\x05*\x03\x10\xe8\aR\x03val\"J\n" +
	"\fTimestampGTE\x12:\n" +
	"\x03val\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\f\xa2Z\t\xb2\x01\x062\x04\x10\xc0\x84=R\x03val\"K\n" +
	"\rTimestampGTLT\x12:\n" +
	"\x03val\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\f\xa2Z\t\xb2\x01\x06\x1a\x02\b\x01*\x00R\x03val\"M\n" +
	"\x0fTimestampExLTGT\x12:\n" +
	"\x03val\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\f\xa2Z\t\xb2\x01\x06\x1a\x00*\x02\b\x01R\x03val\"P\n" +
	"\x0fTimestampGTELTE\x12=\n" +
	"\x03val\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\x0f\xa2Z\f\xb2\x01\t\"\x03\b\x90\x1c2\x02\b<R\x03val\"R\n" +
	"\x11TimestampExGTELTE\x12=\n" +
	"\x03val\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\x0f\xa2Z\f\xb2\x01\t\"\x02\b<2\x03\b\x90\x1cR\x03val\"H\n" +
	"\x0eTimestampLTNow\x126\n" +
	"\x03val\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\b\xa2Z\x05\xb2\x01\x028\x01R\x03val\"H\n" +
	"\x0eTimestampGTNow\x126\n" +
	"\x03val\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\b\xa2Z\x05\xb2\x01\x02@\x01R\x03val\"L\n" +
	"\x0fTimestampWithin\x129\n" +
	"\x03val\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\v\xa2Z\b\xb2\x01\x05J\x03\b\x90\x1cR\x03val\"S\n" +
	"\x14TimestampLTNowWithin\x12;\n" +
	"\x03val\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\r\xa2Z\n" +
	"\xb2\x01\a8\x01J\x03\b\x90\x1cR\x03val\"S\n" +
	"\x14TimestampGTNowWithin\x12;\n" +
	"\x03val\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\r\xa2Z\n" +
	"\xb2\x01\a@\x01J\x03\b\x90\x1cR\x03valBGZEgithub.com/ml444/gkit/cmd/protoc-gen-go-validate/tests/cases/go;casesb\x06proto3"

var (
	file_cases_wkt_timestamp_proto_rawDescOnce sync.Once
	file_cases_wkt_timestamp_proto_rawDescData []byte
)

func file_cases_wkt_timestamp_proto_rawDescGZIP() []byte {
	file_cases_wkt_timestamp_proto_rawDescOnce.Do(func() {
		file_cases_wkt_timestamp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cases_wkt_timestamp_proto_rawDesc), len(file_cases_wkt_timestamp_proto_rawDesc)))
	})
	return file_cases_wkt_timestamp_proto_rawDescData
}

var file_cases_wkt_timestamp_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_cases_wkt_timestamp_proto_goTypes = []any{
	(*TimestampNone)(nil),         // 0: tests.cases.TimestampNone
	(*TimestampRequired)(nil),     // 1: tests.cases.TimestampRequired
	(*TimestampConst)(nil),        // 2: tests.cases.TimestampConst
	(*TimestampLT)(nil),           // 3: tests.cases.TimestampLT
	(*TimestampLTE)(nil),          // 4: tests.cases.TimestampLTE
	(*TimestampGT)(nil),           // 5: tests.cases.TimestampGT
	(*TimestampGTE)(nil),          // 6: tests.cases.TimestampGTE
	(*TimestampGTLT)(nil),         // 7: tests.cases.TimestampGTLT
	(*TimestampExLTGT)(nil),       // 8: tests.cases.TimestampExLTGT
	(*TimestampGTELTE)(nil),       // 9: tests.cases.TimestampGTELTE
	(*TimestampExGTELTE)(nil),     // 10: tests.cases.TimestampExGTELTE
	(*TimestampLTNow)(nil),        // 11: tests.cases.TimestampLTNow
	(*TimestampGTNow)(nil),        // 12: tests.cases.TimestampGTNow
	(*TimestampWithin)(nil),       // 13: tests.cases.TimestampWithin
	(*TimestampLTNowWithin)(nil),  // 14: tests.cases.TimestampLTNowWithin
	(*TimestampGTNowWithin)(nil),  // 15: tests.cases.TimestampGTNowWithin
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_cases_wkt_timestamp_proto_depIdxs = []int32{
	16, // 0: tests.cases.TimestampNone.val:type_name -> google.protobuf.Timestamp
	16, // 1: tests.cases.TimestampRequired.val:type_name -> google.protobuf.Timestamp
	16, // 2: tests.cases.TimestampConst.val:type_name -> google.protobuf.Timestamp
	16, // 3: tests.cases.TimestampLT.val:type_name -> google.protobuf.Timestamp
	16, // 4: tests.cases.TimestampLTE.val:type_name -> google.protobuf.Timestamp
	16, // 5: tests.cases.TimestampGT.val:type_name -> google.protobuf.Timestamp
	16, // 6: tests.cases.TimestampGTE.val:type_name -> google.protobuf.Timestamp
	16, // 7: tests.cases.TimestampGTLT.val:type_name -> google.protobuf.Timestamp
	16, // 8: tests.cases.TimestampExLTGT.val:type_name -> google.protobuf.Timestamp
	16, // 9: tests.cases.TimestampGTELTE.val:type_name -> google.protobuf.Timestamp
	16, // 10: tests.cases.TimestampExGTELTE.val:type_name -> google.protobuf.Timestamp
	16, // 11: tests.cases.TimestampLTNow.val:type_name -> google.protobuf.Timestamp
	16, // 12: tests.cases.TimestampGTNow.val:type_name -> google.protobuf.Timestamp
	16, // 13: tests.cases.TimestampWithin.val:type_name -> google.protobuf.Timestamp
	16, // 14: tests.cases.TimestampLTNowWithin.val:type_name -> google.protobuf.Timestamp
	16, // 15: tests.cases.TimestampGTNowWithin.val:type_name -> google.protobuf.Timestamp
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_cases_wkt_timestamp_proto_init() }
func file_cases_wkt_timestamp_proto_init() {
	if File_cases_wkt_timestamp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cases_wkt_timestamp_proto_rawDesc), len(file_cases_wkt_timestamp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cases_wkt_timestamp_proto_goTypes,
		DependencyIndexes: file_cases_wkt_timestamp_proto_depIdxs,
		MessageInfos:      file_cases_wkt_timestamp_proto_msgTypes,
	}.Build()
	File_cases_wkt_timestamp_proto = out.File
	file_cases_wkt_timestamp_proto_goTypes = nil
	file_cases_wkt_timestamp_proto_depIdxs = nil
}
