// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: cases/wkt_nested.proto

package cases

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/ml444/gkit/cmd/protoc-gen-go-validate/v"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WktLevelOne struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Two           *WktLevelOne_WktLevelTwo `protobuf:"bytes,1,opt,name=two,proto3" json:"two,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WktLevelOne) Reset() {
	*x = WktLevelOne{}
	mi := &file_cases_wkt_nested_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WktLevelOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WktLevelOne) ProtoMessage() {}

func (x *WktLevelOne) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_nested_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WktLevelOne.ProtoReflect.Descriptor instead.
func (*WktLevelOne) Descriptor() ([]byte, []int) {
	return file_cases_wkt_nested_proto_rawDescGZIP(), []int{0}
}

func (x *WktLevelOne) GetTwo() *WktLevelOne_WktLevelTwo {
	if x != nil {
		return x.Two
	}
	return nil
}

type WktLevelOne_WktLevelTwo struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Three         *WktLevelOne_WktLevelTwo_WktLevelThree `protobuf:"bytes,1,opt,name=three,proto3" json:"three,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WktLevelOne_WktLevelTwo) Reset() {
	*x = WktLevelOne_WktLevelTwo{}
	mi := &file_cases_wkt_nested_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WktLevelOne_WktLevelTwo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WktLevelOne_WktLevelTwo) ProtoMessage() {}

func (x *WktLevelOne_WktLevelTwo) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_nested_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WktLevelOne_WktLevelTwo.ProtoReflect.Descriptor instead.
func (*WktLevelOne_WktLevelTwo) Descriptor() ([]byte, []int) {
	return file_cases_wkt_nested_proto_rawDescGZIP(), []int{0, 0}
}

func (x *WktLevelOne_WktLevelTwo) GetThree() *WktLevelOne_WktLevelTwo_WktLevelThree {
	if x != nil {
		return x.Three
	}
	return nil
}

type WktLevelOne_WktLevelTwo_WktLevelThree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WktLevelOne_WktLevelTwo_WktLevelThree) Reset() {
	*x = WktLevelOne_WktLevelTwo_WktLevelThree{}
	mi := &file_cases_wkt_nested_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WktLevelOne_WktLevelTwo_WktLevelThree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WktLevelOne_WktLevelTwo_WktLevelThree) ProtoMessage() {}

func (x *WktLevelOne_WktLevelTwo_WktLevelThree) ProtoReflect() protoreflect.Message {
	mi := &file_cases_wkt_nested_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WktLevelOne_WktLevelTwo_WktLevelThree.ProtoReflect.Descriptor instead.
func (*WktLevelOne_WktLevelTwo_WktLevelThree) Descriptor() ([]byte, []int) {
	return file_cases_wkt_nested_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *WktLevelOne_WktLevelTwo_WktLevelThree) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_cases_wkt_nested_proto protoreflect.FileDescriptor

const file_cases_wkt_nested_proto_rawDesc = "" +
	"\n" +
	"\x16cases/wkt_nested.proto\x12\vtests.cases\x1a\tv/v.proto\"\xe2\x01\n" +
	"\vWktLevelOne\x12@\n" +
	"\x03two\x18\x01 \x01(\v2$.tests.cases.WktLevelOne.WktLevelTwoB\b\xa2Z\x05\x8a\x01\x02\x10\x01R\x03two\x1a\x90\x01\n" +
	"\vWktLevelTwo\x12R\n" +
	"\x05three\x18\x01 \x01(\v22.tests.cases.WktLevelOne.WktLevelTwo.WktLevelThreeB\b\xa2Z\x05\x8a\x01\x02\x10\x01R\x05three\x1a-\n" +
	"\rWktLevelThree\x12\x1c\n" +
	"\x04uuid\x18\x01 \x01(\tB\b\xa2Z\x05r\x03\xb0\x01\x01R\x04uuidBGZEgithub.com/ml444/gkit/cmd/protoc-gen-go-validate/tests/cases/go;casesb\x06proto3"

var (
	file_cases_wkt_nested_proto_rawDescOnce sync.Once
	file_cases_wkt_nested_proto_rawDescData []byte
)

func file_cases_wkt_nested_proto_rawDescGZIP() []byte {
	file_cases_wkt_nested_proto_rawDescOnce.Do(func() {
		file_cases_wkt_nested_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cases_wkt_nested_proto_rawDesc), len(file_cases_wkt_nested_proto_rawDesc)))
	})
	return file_cases_wkt_nested_proto_rawDescData
}

var file_cases_wkt_nested_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cases_wkt_nested_proto_goTypes = []any{
	(*WktLevelOne)(nil),                           // 0: tests.cases.WktLevelOne
	(*WktLevelOne_WktLevelTwo)(nil),               // 1: tests.cases.WktLevelOne.WktLevelTwo
	(*WktLevelOne_WktLevelTwo_WktLevelThree)(nil), // 2: tests.cases.WktLevelOne.WktLevelTwo.WktLevelThree
}
var file_cases_wkt_nested_proto_depIdxs = []int32{
	1, // 0: tests.cases.WktLevelOne.two:type_name -> tests.cases.WktLevelOne.WktLevelTwo
	2, // 1: tests.cases.WktLevelOne.WktLevelTwo.three:type_name -> tests.cases.WktLevelOne.WktLevelTwo.WktLevelThree
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cases_wkt_nested_proto_init() }
func file_cases_wkt_nested_proto_init() {
	if File_cases_wkt_nested_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cases_wkt_nested_proto_rawDesc), len(file_cases_wkt_nested_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cases_wkt_nested_proto_goTypes,
		DependencyIndexes: file_cases_wkt_nested_proto_depIdxs,
		MessageInfos:      file_cases_wkt_nested_proto_msgTypes,
	}.Build()
	File_cases_wkt_nested_proto = out.File
	file_cases_wkt_nested_proto_goTypes = nil
	file_cases_wkt_nested_proto_depIdxs = nil
}
