// Code generated by protoc-gen-go-validate. DO NOT EDIT.
// - protoc-gen-go-validate 1.0.0
// - protoc             v6.30.2
// source: cases/wkt_nested.proto

package cases

import (
	"errors"
	"fmt"
	"net"
	"net/url"
	"regexp"
	"strings"
	"unicode/utf8"

	"github.com/ml444/gkit/errorx"
)

// ensure the imports are used
var (
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = (*url.URL)(nil)
)

// define the regex for a UUID once up-front
var wkt_nested_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

func wkt_nested_validateUuid(uuid string) error {
	if matched := wkt_nested_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}
	return nil
}

func wkt_nestedValidationError(errCode int32, msg string, cause error) error {
	err := errorx.CreateError(400, errCode, msg)
	if cause != nil {
		err = err.WithCause(cause)
	}
	return err
}

// wkt_nestedMultiError is an error wrapping multiple validation errors
// returned by .ValidateAll() if the designated constraints aren't met.
type wkt_nestedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m wkt_nestedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m wkt_nestedMultiError) AllErrors() []error { return m }

func (m *WktLevelOne) Validate() error {
	return m.validate(false)
}

func (m *WktLevelOne) ValidateAll() error {
	return m.validate(true)
}

func (m *WktLevelOne) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	if m.GetTwo() == nil {
		err := wkt_nestedValidationError(
			0,
			"[Two] value is required",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTwo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, wkt_nestedValidationError(
					0,
					"embedded message failed validation",
					err,
				))
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, wkt_nestedValidationError(
					0,
					"embedded message failed validation",
					err,
				))
			}
		}
	} else if v, ok := interface{}(m.GetTwo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return wkt_nestedValidationError(
				0,
				"embedded message failed validation",
				err,
			)
		}
	}

	if len(errors) > 0 {
		return wkt_nestedMultiError(errors)
	}
	return nil
}

func (m *WktLevelOne_WktLevelTwo) Validate() error {
	return m.validate(false)
}

func (m *WktLevelOne_WktLevelTwo) ValidateAll() error {
	return m.validate(true)
}

func (m *WktLevelOne_WktLevelTwo) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error
	if m.GetThree() == nil {
		err := wkt_nestedValidationError(
			0,
			"[Three] value is required",
			nil,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetThree()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, wkt_nestedValidationError(
					0,
					"embedded message failed validation",
					err,
				))
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, wkt_nestedValidationError(
					0,
					"embedded message failed validation",
					err,
				))
			}
		}
	} else if v, ok := interface{}(m.GetThree()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return wkt_nestedValidationError(
				0,
				"embedded message failed validation",
				err,
			)
		}
	}

	if len(errors) > 0 {
		return wkt_nestedMultiError(errors)
	}
	return nil
}

func (m *WktLevelOne_WktLevelTwo_WktLevelThree) Validate() error {
	return m.validate(false)
}

func (m *WktLevelOne_WktLevelTwo_WktLevelThree) ValidateAll() error {
	return m.validate(true)
}

func (m *WktLevelOne_WktLevelTwo_WktLevelThree) validate(all bool) error {
	if m == nil {
		return nil
	}
	var errors []error

	if e := wkt_nested_validateUuid(m.GetUuid()); e != nil {
		err := wkt_nestedValidationError(
			0,
			"[Uuid] value must be a valid UUID",
			e,
		)
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return wkt_nestedMultiError(errors)
	}
	return nil
}
